// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Keap.OpenApiClient.Rest.V2.Affiliates;
using Soenneker.Keap.OpenApiClient.Rest.V2.AutomationCategory;
using Soenneker.Keap.OpenApiClient.Rest.V2.Automations;
using Soenneker.Keap.OpenApiClient.Rest.V2.BusinessProfile;
using Soenneker.Keap.OpenApiClient.Rest.V2.Campaigns;
using Soenneker.Keap.OpenApiClient.Rest.V2.Companies;
using Soenneker.Keap.OpenApiClient.Rest.V2.Contacts;
using Soenneker.Keap.OpenApiClient.Rest.V2.ContactsLink;
using Soenneker.Keap.OpenApiClient.Rest.V2.ContactsMerge;
using Soenneker.Keap.OpenApiClient.Rest.V2.ContactsUnlink;
using Soenneker.Keap.OpenApiClient.Rest.V2.Discounts;
using Soenneker.Keap.OpenApiClient.Rest.V2.EasyAutomations;
using Soenneker.Keap.OpenApiClient.Rest.V2.EmailAddresses;
using Soenneker.Keap.OpenApiClient.Rest.V2.Emails;
using Soenneker.Keap.OpenApiClient.Rest.V2.EmailsBatchAdd;
using Soenneker.Keap.OpenApiClient.Rest.V2.EmailsBatchRemove;
using Soenneker.Keap.OpenApiClient.Rest.V2.EmailsSend;
using Soenneker.Keap.OpenApiClient.Rest.V2.Files;
using Soenneker.Keap.OpenApiClient.Rest.V2.Integrations;
using Soenneker.Keap.OpenApiClient.Rest.V2.LeadSourceCategories;
using Soenneker.Keap.OpenApiClient.Rest.V2.LeadSources;
using Soenneker.Keap.OpenApiClient.Rest.V2.Locales;
using Soenneker.Keap.OpenApiClient.Rest.V2.Merchants;
using Soenneker.Keap.OpenApiClient.Rest.V2.Notes;
using Soenneker.Keap.OpenApiClient.Rest.V2.Oauth;
using Soenneker.Keap.OpenApiClient.Rest.V2.Opportunities;
using Soenneker.Keap.OpenApiClient.Rest.V2.Orders;
using Soenneker.Keap.OpenApiClient.Rest.V2.PaymentMethodConfigs;
using Soenneker.Keap.OpenApiClient.Rest.V2.PaymentMethods;
using Soenneker.Keap.OpenApiClient.Rest.V2.ProductCategories;
using Soenneker.Keap.OpenApiClient.Rest.V2.ProductInterestBundles;
using Soenneker.Keap.OpenApiClient.Rest.V2.Products;
using Soenneker.Keap.OpenApiClient.Rest.V2.Referrals;
using Soenneker.Keap.OpenApiClient.Rest.V2.Reporting;
using Soenneker.Keap.OpenApiClient.Rest.V2.Sales;
using Soenneker.Keap.OpenApiClient.Rest.V2.Settings;
using Soenneker.Keap.OpenApiClient.Rest.V2.Shipping;
using Soenneker.Keap.OpenApiClient.Rest.V2.Subscriptions;
using Soenneker.Keap.OpenApiClient.Rest.V2.Tags;
using Soenneker.Keap.OpenApiClient.Rest.V2.Tasks;
using Soenneker.Keap.OpenApiClient.Rest.V2.UserGroups;
using Soenneker.Keap.OpenApiClient.Rest.V2.Users;
using Soenneker.Keap.OpenApiClient.Rest.V2.Webforms;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Keap.OpenApiClient.Rest.V2
{
    /// <summary>
    /// Builds and executes requests for operations under \rest\v2
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V2RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The affiliates property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Affiliates.AffiliatesRequestBuilder Affiliates
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Affiliates.AffiliatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The automationCategory property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.AutomationCategory.AutomationCategoryRequestBuilder AutomationCategory
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.AutomationCategory.AutomationCategoryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The automations property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.AutomationsRequestBuilder Automations
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.AutomationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The businessProfile property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.BusinessProfile.BusinessProfileRequestBuilder BusinessProfile
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.BusinessProfile.BusinessProfileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The campaigns property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Campaigns.CampaignsRequestBuilder Campaigns
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Campaigns.CampaignsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The companies property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Companies.CompaniesRequestBuilder Companies
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Companies.CompaniesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The contacts property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Contacts.ContactsRequestBuilder Contacts
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Contacts.ContactsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The contactsLink property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.ContactsLink.ContactsLinkRequestBuilder ContactsLink
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.ContactsLink.ContactsLinkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The contactsMerge property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.ContactsMerge.ContactsMergeRequestBuilder ContactsMerge
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.ContactsMerge.ContactsMergeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The contactsUnlink property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.ContactsUnlink.ContactsUnlinkRequestBuilder ContactsUnlink
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.ContactsUnlink.ContactsUnlinkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The discounts property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Discounts.DiscountsRequestBuilder Discounts
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Discounts.DiscountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The easyAutomations property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.EasyAutomations.EasyAutomationsRequestBuilder EasyAutomations
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.EasyAutomations.EasyAutomationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The emailAddresses property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.EmailAddresses.EmailAddressesRequestBuilder EmailAddresses
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.EmailAddresses.EmailAddressesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The emails property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Emails.EmailsRequestBuilder Emails
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Emails.EmailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The emailsBatchAdd property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.EmailsBatchAdd.EmailsBatchAddRequestBuilder EmailsBatchAdd
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.EmailsBatchAdd.EmailsBatchAddRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The emailsBatchRemove property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.EmailsBatchRemove.EmailsBatchRemoveRequestBuilder EmailsBatchRemove
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.EmailsBatchRemove.EmailsBatchRemoveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The emailsSend property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.EmailsSend.EmailsSendRequestBuilder EmailsSend
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.EmailsSend.EmailsSendRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The files property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Files.FilesRequestBuilder Files
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Files.FilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The integrations property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Integrations.IntegrationsRequestBuilder Integrations
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Integrations.IntegrationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The leadSourceCategories property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.LeadSourceCategories.LeadSourceCategoriesRequestBuilder LeadSourceCategories
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.LeadSourceCategories.LeadSourceCategoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The leadSources property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.LeadSources.LeadSourcesRequestBuilder LeadSources
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.LeadSources.LeadSourcesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The locales property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Locales.LocalesRequestBuilder Locales
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Locales.LocalesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The merchants property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Merchants.MerchantsRequestBuilder Merchants
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Merchants.MerchantsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The notes property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Notes.NotesRequestBuilder Notes
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Notes.NotesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oauth property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Oauth.OauthRequestBuilder Oauth
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Oauth.OauthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The opportunities property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Opportunities.OpportunitiesRequestBuilder Opportunities
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Opportunities.OpportunitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orders property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Orders.OrdersRequestBuilder Orders
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Orders.OrdersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The paymentMethodConfigs property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.PaymentMethodConfigs.PaymentMethodConfigsRequestBuilder PaymentMethodConfigs
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.PaymentMethodConfigs.PaymentMethodConfigsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The paymentMethods property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.PaymentMethods.PaymentMethodsRequestBuilder PaymentMethods
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.PaymentMethods.PaymentMethodsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The productCategories property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.ProductCategories.ProductCategoriesRequestBuilder ProductCategories
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.ProductCategories.ProductCategoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The productInterestBundles property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.ProductInterestBundles.ProductInterestBundlesRequestBuilder ProductInterestBundles
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.ProductInterestBundles.ProductInterestBundlesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The products property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Products.ProductsRequestBuilder Products
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Products.ProductsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The referrals property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Referrals.ReferralsRequestBuilder Referrals
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Referrals.ReferralsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reporting property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Reporting.ReportingRequestBuilder Reporting
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Reporting.ReportingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sales property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Sales.SalesRequestBuilder Sales
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Sales.SalesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The settings property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Settings.SettingsRequestBuilder Settings
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Settings.SettingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The shipping property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Shipping.ShippingRequestBuilder Shipping
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Shipping.ShippingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subscriptions property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Subscriptions.SubscriptionsRequestBuilder Subscriptions
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Subscriptions.SubscriptionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tags property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Tags.TagsRequestBuilder Tags
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Tags.TagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tasks property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Tasks.TasksRequestBuilder Tasks
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Tasks.TasksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The userGroups property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.UserGroups.UserGroupsRequestBuilder UserGroups
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.UserGroups.UserGroupsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Users.UsersRequestBuilder Users
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webforms property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Webforms.WebformsRequestBuilder Webforms
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Webforms.WebformsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Rest.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/v2", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Rest.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/v2", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
