// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Keap.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Keap.OpenApiClient.Rest.V2.Affiliates.Item.Referrals
{
    /// <summary>
    /// Builds and executes requests for operations under \rest\v2\affiliates\{affiliate-id}\referrals
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReferralsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Rest.V2.Affiliates.Item.Referrals.ReferralsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReferralsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/v2/affiliates/{affiliate%2Did}/referrals{?filter*,order_by*,page_size*,page_token*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Rest.V2.Affiliates.Item.Referrals.ReferralsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReferralsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/v2/affiliates/{affiliate%2Did}/referrals{?filter*,order_by*,page_size*,page_token*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves all referrals belonging to the given affiliate
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.ListAffiliateReferralsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 405 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 501 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Keap.OpenApiClient.Models.ListAffiliateReferralsResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Keap.OpenApiClient.Rest.V2.Affiliates.Item.Referrals.ReferralsRequestBuilder.ReferralsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Keap.OpenApiClient.Models.ListAffiliateReferralsResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Keap.OpenApiClient.Rest.V2.Affiliates.Item.Referrals.ReferralsRequestBuilder.ReferralsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "405", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "501", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Keap.OpenApiClient.Models.ListAffiliateReferralsResponse>(requestInfo, global::Soenneker.Keap.OpenApiClient.Models.ListAffiliateReferralsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves all referrals belonging to the given affiliate
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Keap.OpenApiClient.Rest.V2.Affiliates.Item.Referrals.ReferralsRequestBuilder.ReferralsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Keap.OpenApiClient.Rest.V2.Affiliates.Item.Referrals.ReferralsRequestBuilder.ReferralsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Rest.V2.Affiliates.Item.Referrals.ReferralsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Affiliates.Item.Referrals.ReferralsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Keap.OpenApiClient.Rest.V2.Affiliates.Item.Referrals.ReferralsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves all referrals belonging to the given affiliate
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReferralsRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter to apply, allowed fields are:- (String) `source` - Wildcard matching allowedYou will need to apply the `==` operator to check the equality of one of the filters with your searchedword, in the encoded form `%3D%3D`.For fields which allow wildcard matching, you may use the * wildcard character (or its encoded form %2A)for case-insensitive partial matching on text fields. Example of a valid pattern of wildcard usage:- `field==foo*` finds anything in `field` that begins with `foo`For the filters listed above, here are some examples:- `filter=source%3D%3DEmail Marketing`- `filter=source%3D%3DEmail*` (starts with &quot;Email&quot;)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter")]
            public string? Filter { get; set; }
#nullable restore
#else
            [QueryParameter("filter")]
            public string Filter { get; set; }
#endif
            /// <summary>Attribute and direction to order items.One of the following fields:- `id`- `referral_time`One of the following directions:- `asc`- `desc`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("order_by")]
            public string? OrderBy { get; set; }
#nullable restore
#else
            [QueryParameter("order_by")]
            public string OrderBy { get; set; }
#endif
            /// <summary>Total number of items to return per page</summary>
            [QueryParameter("page_size")]
            public int? PageSize { get; set; }
            /// <summary>Page token</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("page_token")]
            public string? PageToken { get; set; }
#nullable restore
#else
            [QueryParameter("page_token")]
            public string PageToken { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
