// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Keap.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Keap.OpenApiClient.Rest.V2.Affiliates.CommissionPrograms.SubscriptionCommissionPrograms.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \rest\v2\affiliates\commissionPrograms\subscriptionCommissionPrograms\{commissionProgramId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithCommissionProgramItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Rest.V2.Affiliates.CommissionPrograms.SubscriptionCommissionPrograms.Item.WithCommissionProgramItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCommissionProgramItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/v2/affiliates/commissionPrograms/subscriptionCommissionPrograms/{commissionProgramId}{?update_mask*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Rest.V2.Affiliates.CommissionPrograms.SubscriptionCommissionPrograms.Item.WithCommissionProgramItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCommissionProgramItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/v2/affiliates/commissionPrograms/subscriptionCommissionPrograms/{commissionProgramId}{?update_mask*}", rawUrl)
        {
        }
        /// <summary>
        /// Updates a Subscription Commission Program
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.GetRestCommissionProgram"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 405 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 501 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Keap.OpenApiClient.Models.GetRestCommissionProgram?> PatchAsync(global::Soenneker.Keap.OpenApiClient.Models.UpdateSubscriptionCommissionProgramRequest body, Action<RequestConfiguration<global::Soenneker.Keap.OpenApiClient.Rest.V2.Affiliates.CommissionPrograms.SubscriptionCommissionPrograms.Item.WithCommissionProgramItemRequestBuilder.WithCommissionProgramItemRequestBuilderPatchQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Keap.OpenApiClient.Models.GetRestCommissionProgram> PatchAsync(global::Soenneker.Keap.OpenApiClient.Models.UpdateSubscriptionCommissionProgramRequest body, Action<RequestConfiguration<global::Soenneker.Keap.OpenApiClient.Rest.V2.Affiliates.CommissionPrograms.SubscriptionCommissionPrograms.Item.WithCommissionProgramItemRequestBuilder.WithCommissionProgramItemRequestBuilderPatchQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "405", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "501", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Keap.OpenApiClient.Models.GetRestCommissionProgram>(requestInfo, global::Soenneker.Keap.OpenApiClient.Models.GetRestCommissionProgram.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Assigns a Subscription Commission Program to a Subscription
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.GetRestCommissionProgram"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 405 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 501 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Keap.OpenApiClient.Models.GetRestCommissionProgram?> PostAsync(global::Soenneker.Keap.OpenApiClient.Models.CreateSubscriptionCommissionProgramRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Keap.OpenApiClient.Models.GetRestCommissionProgram> PostAsync(global::Soenneker.Keap.OpenApiClient.Models.CreateSubscriptionCommissionProgramRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "405", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "501", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Keap.OpenApiClient.Models.GetRestCommissionProgram>(requestInfo, global::Soenneker.Keap.OpenApiClient.Models.GetRestCommissionProgram.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates a Subscription Commission Program
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Keap.OpenApiClient.Models.UpdateSubscriptionCommissionProgramRequest body, Action<RequestConfiguration<global::Soenneker.Keap.OpenApiClient.Rest.V2.Affiliates.CommissionPrograms.SubscriptionCommissionPrograms.Item.WithCommissionProgramItemRequestBuilder.WithCommissionProgramItemRequestBuilderPatchQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Keap.OpenApiClient.Models.UpdateSubscriptionCommissionProgramRequest body, Action<RequestConfiguration<global::Soenneker.Keap.OpenApiClient.Rest.V2.Affiliates.CommissionPrograms.SubscriptionCommissionPrograms.Item.WithCommissionProgramItemRequestBuilder.WithCommissionProgramItemRequestBuilderPatchQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Assigns a Subscription Commission Program to a Subscription
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Keap.OpenApiClient.Models.CreateSubscriptionCommissionProgramRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Keap.OpenApiClient.Models.CreateSubscriptionCommissionProgramRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Rest.V2.Affiliates.CommissionPrograms.SubscriptionCommissionPrograms.Item.WithCommissionProgramItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Affiliates.CommissionPrograms.SubscriptionCommissionPrograms.Item.WithCommissionProgramItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Keap.OpenApiClient.Rest.V2.Affiliates.CommissionPrograms.SubscriptionCommissionPrograms.Item.WithCommissionProgramItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Updates a Subscription Commission Program
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithCommissionProgramItemRequestBuilderPatchQueryParameters 
        {
            /// <summary>An optional list of properties to be updated. If set, only the provided properties will be updated and others will be skipped.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("update_mask")]
            public global::Soenneker.Keap.OpenApiClient.Models.UpdateSubscriptionCommissionProgramUpdateMaskParameterItem[]? UpdateMask { get; set; }
#nullable restore
#else
            [QueryParameter("update_mask")]
            public global::Soenneker.Keap.OpenApiClient.Models.UpdateSubscriptionCommissionProgramUpdateMaskParameterItem[] UpdateMask { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
