// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Keap.OpenApiClient.Models;
using Soenneker.Keap.OpenApiClient.Rest.V2.Automations.BatchUnpublish;
using Soenneker.Keap.OpenApiClient.Rest.V2.Automations.Categories;
using Soenneker.Keap.OpenApiClient.Rest.V2.Automations.Goals;
using Soenneker.Keap.OpenApiClient.Rest.V2.Automations.Ids;
using Soenneker.Keap.OpenApiClient.Rest.V2.Automations.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Keap.OpenApiClient.Rest.V2.Automations
{
    /// <summary>
    /// Builds and executes requests for operations under \rest\v2\automations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AutomationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The batchUnpublish property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.BatchUnpublish.BatchUnpublishRequestBuilder BatchUnpublish
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.BatchUnpublish.BatchUnpublishRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The categories property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.Categories.CategoriesRequestBuilder Categories
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.Categories.CategoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The goals property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.Goals.GoalsRequestBuilder Goals
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.Goals.GoalsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ids property</summary>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.Ids.IdsRequestBuilder Ids
        {
            get => new global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.Ids.IdsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Keap.OpenApiClient.rest.v2.automations.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.Item.WithAutomationItemRequestBuilder"/></returns>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.Item.WithAutomationItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("automationId", position);
                return new global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.Item.WithAutomationItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.AutomationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AutomationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/v2/automations{?filter*,order_by*,page_size*,page_token*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.AutomationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AutomationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/v2/automations{?filter*,order_by*,page_size*,page_token*}", rawUrl)
        {
        }
        /// <summary>
        /// Deletes a single automation
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 405 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 501 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.AutomationsRequestBuilder.AutomationsRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.AutomationsRequestBuilder.AutomationsRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "405", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "501", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves a list of automations
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.ListAutomationResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 405 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Keap.OpenApiClient.Models.Error">When receiving a 501 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Keap.OpenApiClient.Models.ListAutomationResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.AutomationsRequestBuilder.AutomationsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Keap.OpenApiClient.Models.ListAutomationResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.AutomationsRequestBuilder.AutomationsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "405", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "501", global::Soenneker.Keap.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Keap.OpenApiClient.Models.ListAutomationResponse>(requestInfo, global::Soenneker.Keap.OpenApiClient.Models.ListAutomationResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Deletes a single automation
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.AutomationsRequestBuilder.AutomationsRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.AutomationsRequestBuilder.AutomationsRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, "{+baseurl}/rest/v2/automations{?automation_ids*}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Retrieves a list of automations
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.AutomationsRequestBuilder.AutomationsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.AutomationsRequestBuilder.AutomationsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.AutomationsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.AutomationsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Keap.OpenApiClient.Rest.V2.Automations.AutomationsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Deletes a single automation
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AutomationsRequestBuilderDeleteQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            #pragma warning disable CS1591
            [QueryParameter("automation_ids")]
            public long?[]? AutomationIds { get; set; }
            #pragma warning restore CS1591
#nullable restore
#else
            #pragma warning disable CS1591
            [QueryParameter("automation_ids")]
            public long?[] AutomationIds { get; set; }
            #pragma warning restore CS1591
#endif
        }
        /// <summary>
        /// Retrieves a list of automations
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AutomationsRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter to apply, allowed fields are:- `name` (String): Filter by automation name. Supports the `==` operator with optional prefix wildcard (`foo*`).  Without a wildcard, the search matches automations whose name contains the given text.  With a prefix wildcard, it matches automations whose name starts with the given text.  - `filter=name%3D%3DSpring Automation` — names containing &quot;Spring Automation&quot;  - `filter=name%3D%3DSpring*` — names starting with &quot;Spring&quot;- `id` (Long): Filter by automation ID. Supports comparison operators:  `==` `!=` `&gt;` `&lt;` `&gt;=` `&lt;=`  - `filter=id%3E5` — id &gt; 5  - `filter=id%3E%3D10` — id &gt;= 10- `status` (String): Filter by automation status. Accepted values: `published`, `draft`.  - `filter=status%3D%3Dpublished` — published automations only  - `filter=status%3D%3Ddraft` — draft automations only- `categories` (String): Filter by category ID (comma-separated list of IDs).  - `filter=categories%3D%3D1` — automations in category 1  - `filter=categories%3D%3D1,2,3` — automations in categories 1, 2, or 3Multiple filters can be combined with `;` (AND logic):- `filter=name%3D%3DSpring*%3Bautomation_id%3E5`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter")]
            public string? Filter { get; set; }
#nullable restore
#else
            [QueryParameter("filter")]
            public string Filter { get; set; }
#endif
            /// <summary>Attribute and direction to order items.One of the following fields:- `name`- `category`- `activeContacts`- `publishedDate`One of the following directions:- `asc`- `desc`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("order_by")]
            public string? OrderBy { get; set; }
#nullable restore
#else
            [QueryParameter("order_by")]
            public string OrderBy { get; set; }
#endif
            /// <summary>Total number of items to return per page</summary>
            [QueryParameter("page_size")]
            public int? PageSize { get; set; }
            /// <summary>Page token</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("page_token")]
            public string? PageToken { get; set; }
#nullable restore
#else
            [QueryParameter("page_token")]
            public string PageToken { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
