// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApplicationConfigurationModuleApplication : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The company property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Keap.OpenApiClient.Models.ApplicationCompany? Company { get; set; }
#nullable restore
#else
        public global::Soenneker.Keap.OpenApiClient.Models.ApplicationCompany Company { get; set; }
#endif
        /// <summary>The default_view_locale property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultViewLocale { get; set; }
#nullable restore
#else
        public string DefaultViewLocale { get; set; }
#endif
        /// <summary>The features_enabled property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Keap.OpenApiClient.Models.ApplicationFeaturesEnabled? FeaturesEnabled { get; set; }
#nullable restore
#else
        public global::Soenneker.Keap.OpenApiClient.Models.ApplicationFeaturesEnabled FeaturesEnabled { get; set; }
#endif
        /// <summary>The time_zone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeZone { get; set; }
#nullable restore
#else
        public string TimeZone { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Models.ApplicationConfigurationModuleApplication"/> and sets the default values.
        /// </summary>
        public ApplicationConfigurationModuleApplication()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.ApplicationConfigurationModuleApplication"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Keap.OpenApiClient.Models.ApplicationConfigurationModuleApplication CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Keap.OpenApiClient.Models.ApplicationConfigurationModuleApplication();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "company", n => { Company = n.GetObjectValue<global::Soenneker.Keap.OpenApiClient.Models.ApplicationCompany>(global::Soenneker.Keap.OpenApiClient.Models.ApplicationCompany.CreateFromDiscriminatorValue); } },
                { "default_view_locale", n => { DefaultViewLocale = n.GetStringValue(); } },
                { "features_enabled", n => { FeaturesEnabled = n.GetObjectValue<global::Soenneker.Keap.OpenApiClient.Models.ApplicationFeaturesEnabled>(global::Soenneker.Keap.OpenApiClient.Models.ApplicationFeaturesEnabled.CreateFromDiscriminatorValue); } },
                { "time_zone", n => { TimeZone = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Keap.OpenApiClient.Models.ApplicationCompany>("company", Company);
            writer.WriteStringValue("default_view_locale", DefaultViewLocale);
            writer.WriteObjectValue<global::Soenneker.Keap.OpenApiClient.Models.ApplicationFeaturesEnabled>("features_enabled", FeaturesEnabled);
            writer.WriteStringValue("time_zone", TimeZone);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
