// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApplicationConfigurationModuleEcommerce : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The credit_card_types property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreditCardTypes { get; set; }
#nullable restore
#else
        public string CreditCardTypes { get; set; }
#endif
        /// <summary>The currency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>The default_charge_max_retry_attempts property</summary>
        public int? DefaultChargeMaxRetryAttempts { get; set; }
        /// <summary>The default_country property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultCountry { get; set; }
#nullable restore
#else
        public string DefaultCountry { get; set; }
#endif
        /// <summary>The default_merchant property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultMerchant { get; set; }
#nullable restore
#else
        public string DefaultMerchant { get; set; }
#endif
        /// <summary>The default_number_of_days_between_charge_attempts property</summary>
        public int? DefaultNumberOfDaysBetweenChargeAttempts { get; set; }
        /// <summary>The default_tax property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultTax { get; set; }
#nullable restore
#else
        public string DefaultTax { get; set; }
#endif
        /// <summary>The default_to_auto_charge property</summary>
        public bool? DefaultToAutoCharge { get; set; }
        /// <summary>The merchant_account_max_retry_attempts property</summary>
        public int? MerchantAccountMaxRetryAttempts { get; set; }
        /// <summary>The payment_types property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentTypes { get; set; }
#nullable restore
#else
        public string PaymentTypes { get; set; }
#endif
        /// <summary>The promo_codes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PromoCodes { get; set; }
#nullable restore
#else
        public string PromoCodes { get; set; }
#endif
        /// <summary>The track_cost_per_unit property</summary>
        public bool? TrackCostPerUnit { get; set; }
        /// <summary>The track_inventory property</summary>
        public bool? TrackInventory { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Models.ApplicationConfigurationModuleEcommerce"/> and sets the default values.
        /// </summary>
        public ApplicationConfigurationModuleEcommerce()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.ApplicationConfigurationModuleEcommerce"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Keap.OpenApiClient.Models.ApplicationConfigurationModuleEcommerce CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Keap.OpenApiClient.Models.ApplicationConfigurationModuleEcommerce();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "credit_card_types", n => { CreditCardTypes = n.GetStringValue(); } },
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "default_charge_max_retry_attempts", n => { DefaultChargeMaxRetryAttempts = n.GetIntValue(); } },
                { "default_country", n => { DefaultCountry = n.GetStringValue(); } },
                { "default_merchant", n => { DefaultMerchant = n.GetStringValue(); } },
                { "default_number_of_days_between_charge_attempts", n => { DefaultNumberOfDaysBetweenChargeAttempts = n.GetIntValue(); } },
                { "default_tax", n => { DefaultTax = n.GetStringValue(); } },
                { "default_to_auto_charge", n => { DefaultToAutoCharge = n.GetBoolValue(); } },
                { "merchant_account_max_retry_attempts", n => { MerchantAccountMaxRetryAttempts = n.GetIntValue(); } },
                { "payment_types", n => { PaymentTypes = n.GetStringValue(); } },
                { "promo_codes", n => { PromoCodes = n.GetStringValue(); } },
                { "track_cost_per_unit", n => { TrackCostPerUnit = n.GetBoolValue(); } },
                { "track_inventory", n => { TrackInventory = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("credit_card_types", CreditCardTypes);
            writer.WriteStringValue("currency", Currency);
            writer.WriteIntValue("default_charge_max_retry_attempts", DefaultChargeMaxRetryAttempts);
            writer.WriteStringValue("default_country", DefaultCountry);
            writer.WriteStringValue("default_merchant", DefaultMerchant);
            writer.WriteIntValue("default_number_of_days_between_charge_attempts", DefaultNumberOfDaysBetweenChargeAttempts);
            writer.WriteStringValue("default_tax", DefaultTax);
            writer.WriteBoolValue("default_to_auto_charge", DefaultToAutoCharge);
            writer.WriteIntValue("merchant_account_max_retry_attempts", MerchantAccountMaxRetryAttempts);
            writer.WriteStringValue("payment_types", PaymentTypes);
            writer.WriteStringValue("promo_codes", PromoCodes);
            writer.WriteBoolValue("track_cost_per_unit", TrackCostPerUnit);
            writer.WriteBoolValue("track_inventory", TrackInventory);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
