// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    /// <summary>The publication status of the automation</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AutomationStatus
    {
        [EnumMember(Value = "PUBLISHED")]
        #pragma warning disable CS1591
        Published,
        #pragma warning restore CS1591
        [EnumMember(Value = "DRAFT")]
        #pragma warning disable CS1591
        Draft,
        #pragma warning restore CS1591
    }
}
