// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    /// <summary>The type of payment method. For now, only CARD is supported.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CardPaymentMethodType
    {
        [EnumMember(Value = "CARD")]
        #pragma warning disable CS1591
        Card,
        #pragma warning restore CS1591
    }
}
