// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Contact : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The account_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountId { get; set; }
#nullable restore
#else
        public string AccountId { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The addresses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Keap.OpenApiClient.Models.Address>? Addresses { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Keap.OpenApiClient.Models.Address> Addresses { get; set; }
#endif
        /// <summary>The anniversary date</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnniversaryDate { get; set; }
#nullable restore
#else
        public string AnniversaryDate { get; set; }
#endif
        /// <summary>The assistant_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssistantName { get; set; }
#nullable restore
#else
        public string AssistantName { get; set; }
#endif
        /// <summary>The assistant_phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssistantPhone { get; set; }
#nullable restore
#else
        public string AssistantPhone { get; set; }
#endif
        /// <summary>The billing_information property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillingInformation { get; set; }
#nullable restore
#else
        public string BillingInformation { get; set; }
#endif
        /// <summary>The birth date</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BirthDate { get; set; }
#nullable restore
#else
        public string BirthDate { get; set; }
#endif
        /// <summary>Associated company</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Keap.OpenApiClient.Models.BasicCompany? Company { get; set; }
#nullable restore
#else
        public global::Soenneker.Keap.OpenApiClient.Models.BasicCompany Company { get; set; }
#endif
        /// <summary>Type of contact</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactType { get; set; }
#nullable restore
#else
        public string ContactType { get; set; }
#endif
        /// <summary>The created_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>Creation timestamp (ISO-8601)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreateTime { get; set; }
#nullable restore
#else
        public string CreateTime { get; set; }
#endif
        /// <summary>The custom_fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Keap.OpenApiClient.Models.CustomFieldValue>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Keap.OpenApiClient.Models.CustomFieldValue> CustomFields { get; set; }
#endif
        /// <summary>The email_addresses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Keap.OpenApiClient.Models.EmailAddress>? EmailAddresses { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Keap.OpenApiClient.Models.EmailAddress> EmailAddresses { get; set; }
#endif
        /// <summary>Last name / surname</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FamilyName { get; set; }
#nullable restore
#else
        public string FamilyName { get; set; }
#endif
        /// <summary>The fax_numbers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Keap.OpenApiClient.Models.FaxNumber>? FaxNumbers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Keap.OpenApiClient.Models.FaxNumber> FaxNumbers { get; set; }
#endif
        /// <summary>First name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GivenName { get; set; }
#nullable restore
#else
        public string GivenName { get; set; }
#endif
        /// <summary>The groups property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Groups { get; set; }
#nullable restore
#else
        public string Groups { get; set; }
#endif
        /// <summary>Unique identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Job title</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JobTitle { get; set; }
#nullable restore
#else
        public string JobTitle { get; set; }
#endif
        /// <summary>The last_updated_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastUpdatedBy { get; set; }
#nullable restore
#else
        public string LastUpdatedBy { get; set; }
#endif
        /// <summary>Lead source identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeadsourceId { get; set; }
#nullable restore
#else
        public string LeadsourceId { get; set; }
#endif
        /// <summary>The links property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Keap.OpenApiClient.Models.Link>? Links { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Keap.OpenApiClient.Models.Link> Links { get; set; }
#endif
        /// <summary>Middle name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MiddleName { get; set; }
#nullable restore
#else
        public string MiddleName { get; set; }
#endif
        /// <summary>The origin property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Keap.OpenApiClient.Models.Origin? Origin { get; set; }
#nullable restore
#else
        public global::Soenneker.Keap.OpenApiClient.Models.Origin Origin { get; set; }
#endif
        /// <summary>ID of the user who owns this contact</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OwnerId { get; set; }
#nullable restore
#else
        public string OwnerId { get; set; }
#endif
        /// <summary>The phone_numbers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Keap.OpenApiClient.Models.PhoneNumber>? PhoneNumbers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Keap.OpenApiClient.Models.PhoneNumber> PhoneNumbers { get; set; }
#endif
        /// <summary>Preferred locale</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreferredLocale { get; set; }
#nullable restore
#else
        public string PreferredLocale { get; set; }
#endif
        /// <summary>Preferred name or nickname</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreferredName { get; set; }
#nullable restore
#else
        public string PreferredName { get; set; }
#endif
        /// <summary>Name prefix</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prefix { get; set; }
#nullable restore
#else
        public string Prefix { get; set; }
#endif
        /// <summary>Referral code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReferralCode { get; set; }
#nullable restore
#else
        public string ReferralCode { get; set; }
#endif
        /// <summary>Contact score value</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScoreValue { get; set; }
#nullable restore
#else
        public string ScoreValue { get; set; }
#endif
        /// <summary>The social_accounts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Keap.OpenApiClient.Models.SocialAccount>? SocialAccounts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Keap.OpenApiClient.Models.SocialAccount> SocialAccounts { get; set; }
#endif
        /// <summary>The source_type property</summary>
        public global::Soenneker.Keap.OpenApiClient.Models.ContactSourceType? SourceType { get; set; }
        /// <summary>Spouse&apos;s name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SpouseName { get; set; }
#nullable restore
#else
        public string SpouseName { get; set; }
#endif
        /// <summary>Name suffix</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Suffix { get; set; }
#nullable restore
#else
        public string Suffix { get; set; }
#endif
        /// <summary>The tag_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TagIds { get; set; }
#nullable restore
#else
        public List<string> TagIds { get; set; }
#endif
        /// <summary>Contact&apos;s timezone</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeZone { get; set; }
#nullable restore
#else
        public string TimeZone { get; set; }
#endif
        /// <summary>Last update timestamp (ISO-8601)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdateTime { get; set; }
#nullable restore
#else
        public string UpdateTime { get; set; }
#endif
        /// <summary>The utm_parameters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Keap.OpenApiClient.Models.ContactUtmResponse>? UtmParameters { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Keap.OpenApiClient.Models.ContactUtmResponse> UtmParameters { get; set; }
#endif
        /// <summary>Personal website URL</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Website { get; set; }
#nullable restore
#else
        public string Website { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Models.Contact"/> and sets the default values.
        /// </summary>
        public Contact()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.Contact"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Keap.OpenApiClient.Models.Contact CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Keap.OpenApiClient.Models.Contact();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_id", n => { AccountId = n.GetStringValue(); } },
                { "addresses", n => { Addresses = n.GetCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.Address>(global::Soenneker.Keap.OpenApiClient.Models.Address.CreateFromDiscriminatorValue)?.AsList(); } },
                { "anniversary_date", n => { AnniversaryDate = n.GetStringValue(); } },
                { "assistant_name", n => { AssistantName = n.GetStringValue(); } },
                { "assistant_phone", n => { AssistantPhone = n.GetStringValue(); } },
                { "billing_information", n => { BillingInformation = n.GetStringValue(); } },
                { "birth_date", n => { BirthDate = n.GetStringValue(); } },
                { "company", n => { Company = n.GetObjectValue<global::Soenneker.Keap.OpenApiClient.Models.BasicCompany>(global::Soenneker.Keap.OpenApiClient.Models.BasicCompany.CreateFromDiscriminatorValue); } },
                { "contact_type", n => { ContactType = n.GetStringValue(); } },
                { "create_time", n => { CreateTime = n.GetStringValue(); } },
                { "created_by", n => { CreatedBy = n.GetStringValue(); } },
                { "custom_fields", n => { CustomFields = n.GetCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.CustomFieldValue>(global::Soenneker.Keap.OpenApiClient.Models.CustomFieldValue.CreateFromDiscriminatorValue)?.AsList(); } },
                { "email_addresses", n => { EmailAddresses = n.GetCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.EmailAddress>(global::Soenneker.Keap.OpenApiClient.Models.EmailAddress.CreateFromDiscriminatorValue)?.AsList(); } },
                { "family_name", n => { FamilyName = n.GetStringValue(); } },
                { "fax_numbers", n => { FaxNumbers = n.GetCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.FaxNumber>(global::Soenneker.Keap.OpenApiClient.Models.FaxNumber.CreateFromDiscriminatorValue)?.AsList(); } },
                { "given_name", n => { GivenName = n.GetStringValue(); } },
                { "groups", n => { Groups = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "job_title", n => { JobTitle = n.GetStringValue(); } },
                { "last_updated_by", n => { LastUpdatedBy = n.GetStringValue(); } },
                { "leadsource_id", n => { LeadsourceId = n.GetStringValue(); } },
                { "links", n => { Links = n.GetCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.Link>(global::Soenneker.Keap.OpenApiClient.Models.Link.CreateFromDiscriminatorValue)?.AsList(); } },
                { "middle_name", n => { MiddleName = n.GetStringValue(); } },
                { "origin", n => { Origin = n.GetObjectValue<global::Soenneker.Keap.OpenApiClient.Models.Origin>(global::Soenneker.Keap.OpenApiClient.Models.Origin.CreateFromDiscriminatorValue); } },
                { "owner_id", n => { OwnerId = n.GetStringValue(); } },
                { "phone_numbers", n => { PhoneNumbers = n.GetCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.PhoneNumber>(global::Soenneker.Keap.OpenApiClient.Models.PhoneNumber.CreateFromDiscriminatorValue)?.AsList(); } },
                { "preferred_locale", n => { PreferredLocale = n.GetStringValue(); } },
                { "preferred_name", n => { PreferredName = n.GetStringValue(); } },
                { "prefix", n => { Prefix = n.GetStringValue(); } },
                { "referral_code", n => { ReferralCode = n.GetStringValue(); } },
                { "score_value", n => { ScoreValue = n.GetStringValue(); } },
                { "social_accounts", n => { SocialAccounts = n.GetCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.SocialAccount>(global::Soenneker.Keap.OpenApiClient.Models.SocialAccount.CreateFromDiscriminatorValue)?.AsList(); } },
                { "source_type", n => { SourceType = n.GetEnumValue<global::Soenneker.Keap.OpenApiClient.Models.ContactSourceType>(); } },
                { "spouse_name", n => { SpouseName = n.GetStringValue(); } },
                { "suffix", n => { Suffix = n.GetStringValue(); } },
                { "tag_ids", n => { TagIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "time_zone", n => { TimeZone = n.GetStringValue(); } },
                { "update_time", n => { UpdateTime = n.GetStringValue(); } },
                { "utm_parameters", n => { UtmParameters = n.GetCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.ContactUtmResponse>(global::Soenneker.Keap.OpenApiClient.Models.ContactUtmResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "website", n => { Website = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account_id", AccountId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.Address>("addresses", Addresses);
            writer.WriteStringValue("anniversary_date", AnniversaryDate);
            writer.WriteStringValue("assistant_name", AssistantName);
            writer.WriteStringValue("assistant_phone", AssistantPhone);
            writer.WriteStringValue("billing_information", BillingInformation);
            writer.WriteStringValue("birth_date", BirthDate);
            writer.WriteObjectValue<global::Soenneker.Keap.OpenApiClient.Models.BasicCompany>("company", Company);
            writer.WriteStringValue("contact_type", ContactType);
            writer.WriteStringValue("created_by", CreatedBy);
            writer.WriteStringValue("create_time", CreateTime);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.CustomFieldValue>("custom_fields", CustomFields);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.EmailAddress>("email_addresses", EmailAddresses);
            writer.WriteStringValue("family_name", FamilyName);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.FaxNumber>("fax_numbers", FaxNumbers);
            writer.WriteStringValue("given_name", GivenName);
            writer.WriteStringValue("groups", Groups);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("job_title", JobTitle);
            writer.WriteStringValue("last_updated_by", LastUpdatedBy);
            writer.WriteStringValue("leadsource_id", LeadsourceId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.Link>("links", Links);
            writer.WriteStringValue("middle_name", MiddleName);
            writer.WriteObjectValue<global::Soenneker.Keap.OpenApiClient.Models.Origin>("origin", Origin);
            writer.WriteStringValue("owner_id", OwnerId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.PhoneNumber>("phone_numbers", PhoneNumbers);
            writer.WriteStringValue("preferred_locale", PreferredLocale);
            writer.WriteStringValue("preferred_name", PreferredName);
            writer.WriteStringValue("prefix", Prefix);
            writer.WriteStringValue("referral_code", ReferralCode);
            writer.WriteStringValue("score_value", ScoreValue);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.SocialAccount>("social_accounts", SocialAccounts);
            writer.WriteEnumValue<global::Soenneker.Keap.OpenApiClient.Models.ContactSourceType>("source_type", SourceType);
            writer.WriteStringValue("spouse_name", SpouseName);
            writer.WriteStringValue("suffix", Suffix);
            writer.WriteCollectionOfPrimitiveValues<string>("tag_ids", TagIds);
            writer.WriteStringValue("time_zone", TimeZone);
            writer.WriteStringValue("update_time", UpdateTime);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.ContactUtmResponse>("utm_parameters", UtmParameters);
            writer.WriteStringValue("website", Website);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
