// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ContactSourceType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "SOURCE_TYPE_UNSPECIFIED")]
        #pragma warning disable CS1591
        SourceTypeUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "API")]
        #pragma warning disable CS1591
        Api,
        #pragma warning restore CS1591
        [EnumMember(Value = "APPOINTMENT")]
        #pragma warning disable CS1591
        Appointment,
        #pragma warning restore CS1591
        [EnumMember(Value = "FORM_API_HOSTED")]
        #pragma warning disable CS1591
        FormApiHosted,
        #pragma warning restore CS1591
        [EnumMember(Value = "FORM_API_INTERNAL")]
        #pragma warning disable CS1591
        FormApiInternal,
        #pragma warning restore CS1591
        [EnumMember(Value = "IMPORT")]
        #pragma warning disable CS1591
        Import,
        #pragma warning restore CS1591
        [EnumMember(Value = "INTERNAL_FORM")]
        #pragma warning disable CS1591
        InternalForm,
        #pragma warning restore CS1591
        [EnumMember(Value = "LANDING_PAGE")]
        #pragma warning disable CS1591
        LandingPage,
        #pragma warning restore CS1591
        [EnumMember(Value = "MANUAL")]
        #pragma warning disable CS1591
        Manual,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHER")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNKNOWN")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEBFORM")]
        #pragma warning disable CS1591
        Webform,
        #pragma warning restore CS1591
    }
}
