// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateCustomFieldRequestFieldType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "CURRENCY")]
        #pragma warning disable CS1591
        Currency,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATE")]
        #pragma warning disable CS1591
        Date,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATE_TIME")]
        #pragma warning disable CS1591
        DateTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "DAY_OF_WEEK")]
        #pragma warning disable CS1591
        DayOfWeek,
        #pragma warning restore CS1591
        [EnumMember(Value = "DECIMAL_NUMBER")]
        #pragma warning disable CS1591
        DecimalNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "DRILLDOWN")]
        #pragma warning disable CS1591
        Drilldown,
        #pragma warning restore CS1591
        [EnumMember(Value = "DROPDOWN")]
        #pragma warning disable CS1591
        Dropdown,
        #pragma warning restore CS1591
        [EnumMember(Value = "EMAIL")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "LIST_BOX")]
        #pragma warning disable CS1591
        ListBox,
        #pragma warning restore CS1591
        [EnumMember(Value = "MONTH")]
        #pragma warning disable CS1591
        Month,
        #pragma warning restore CS1591
        [EnumMember(Value = "NAME")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "PERCENT")]
        #pragma warning disable CS1591
        Percent,
        #pragma warning restore CS1591
        [EnumMember(Value = "PHONE_NUMBER")]
        #pragma warning disable CS1591
        PhoneNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "RADIO")]
        #pragma warning disable CS1591
        Radio,
        #pragma warning restore CS1591
        [EnumMember(Value = "SOCIAL_SECURITY_NUMBER")]
        #pragma warning disable CS1591
        SocialSecurityNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "STATE")]
        #pragma warning disable CS1591
        State,
        #pragma warning restore CS1591
        [EnumMember(Value = "TEXT")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
        [EnumMember(Value = "TEXT_AREA")]
        #pragma warning disable CS1591
        TextArea,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER_LIST_BOX")]
        #pragma warning disable CS1591
        UserListBox,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEBSITE")]
        #pragma warning disable CS1591
        Website,
        #pragma warning restore CS1591
        [EnumMember(Value = "WHOLE_NUMBER")]
        #pragma warning disable CS1591
        WholeNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "YEAR")]
        #pragma warning disable CS1591
        Year,
        #pragma warning restore CS1591
        [EnumMember(Value = "YES_NO")]
        #pragma warning disable CS1591
        YesNo,
        #pragma warning restore CS1591
    }
}
