// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateProductOptionRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The order in which this option will be displayed among other options. Minimum is 0. Lower values indicate higher priority in order.</summary>
        public int? DisplayOrder { get; set; }
        /// <summary>Appears only for option_type of LIST. A fixed list of available selectable items for this product option.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Keap.OpenApiClient.Models.CreateProductOptionListOption>? ListItems { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Keap.OpenApiClient.Models.CreateProductOptionListOption> ListItems { get; set; }
#endif
        /// <summary>The displayable name of the option (e.g. Size). Cannot be whitespace only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OptionLabel { get; set; }
#nullable restore
#else
        public string OptionLabel { get; set; }
#endif
        /// <summary>The type of option. Possible valid values are LIST and TEXT.</summary>
        public global::Soenneker.Keap.OpenApiClient.Models.CreateProductOptionRequestOptionType? OptionType { get; set; }
        /// <summary>Whether this option is required for product purchase.</summary>
        public bool? Required { get; set; }
        /// <summary>The option is a user-defined free-form field. The settings define the restrictions on what can be entered.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Keap.OpenApiClient.Models.CreateProductOptionTextOption? TextRules { get; set; }
#nullable restore
#else
        public global::Soenneker.Keap.OpenApiClient.Models.CreateProductOptionTextOption TextRules { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Models.CreateProductOptionRequest"/> and sets the default values.
        /// </summary>
        public CreateProductOptionRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            Required = false;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.CreateProductOptionRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Keap.OpenApiClient.Models.CreateProductOptionRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Keap.OpenApiClient.Models.CreateProductOptionRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "display_order", n => { DisplayOrder = n.GetIntValue(); } },
                { "list_items", n => { ListItems = n.GetCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.CreateProductOptionListOption>(global::Soenneker.Keap.OpenApiClient.Models.CreateProductOptionListOption.CreateFromDiscriminatorValue)?.AsList(); } },
                { "option_label", n => { OptionLabel = n.GetStringValue(); } },
                { "option_type", n => { OptionType = n.GetEnumValue<global::Soenneker.Keap.OpenApiClient.Models.CreateProductOptionRequestOptionType>(); } },
                { "required", n => { Required = n.GetBoolValue(); } },
                { "text_rules", n => { TextRules = n.GetObjectValue<global::Soenneker.Keap.OpenApiClient.Models.CreateProductOptionTextOption>(global::Soenneker.Keap.OpenApiClient.Models.CreateProductOptionTextOption.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("display_order", DisplayOrder);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.CreateProductOptionListOption>("list_items", ListItems);
            writer.WriteStringValue("option_label", OptionLabel);
            writer.WriteEnumValue<global::Soenneker.Keap.OpenApiClient.Models.CreateProductOptionRequestOptionType>("option_type", OptionType);
            writer.WriteBoolValue("required", Required);
            writer.WriteObjectValue<global::Soenneker.Keap.OpenApiClient.Models.CreateProductOptionTextOption>("text_rules", TextRules);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
