// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    /// <summary>
    /// The email request that failed
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateEmailSentRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>When a link in the email was clicked, in ISO-8601 format</summary>
        public DateTimeOffset? ClickedTime { get; set; }
        /// <summary>The contact ID who received the email</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactId { get; set; }
#nullable restore
#else
        public string ContactId { get; set; }
#endif
        /// <summary>Email headers</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Headers { get; set; }
#nullable restore
#else
        public string Headers { get; set; }
#endif
        /// <summary>Base64 encoded HTML</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HtmlContent { get; set; }
#nullable restore
#else
        public string HtmlContent { get; set; }
#endif
        /// <summary>When the email was opened, in ISO-8601 format</summary>
        public DateTimeOffset? OpenedTime { get; set; }
        /// <summary>Provider that sent the email, defaults to UNKNOWN</summary>
        public global::Soenneker.Keap.OpenApiClient.Models.CreateEmailSentRequestOriginalProvider? OriginalProvider { get; set; }
        /// <summary>Provider id that sent the email, must be unique when combined with provider. If omitted a UUID without dashes is autogenerated for the record.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginalProviderId { get; set; }
#nullable restore
#else
        public string OriginalProviderId { get; set; }
#endif
        /// <summary>Base64 encoded text</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlainContent { get; set; }
#nullable restore
#else
        public string PlainContent { get; set; }
#endif
        /// <summary>The email address of the synced email account that generated this message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProviderSourceId { get; set; }
#nullable restore
#else
        public string ProviderSourceId { get; set; }
#endif
        /// <summary>When the email was received, in ISO-8601 format</summary>
        public DateTimeOffset? ReceivedTime { get; set; }
        /// <summary>The sender&apos;s email address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SentFromAddress { get; set; }
#nullable restore
#else
        public string SentFromAddress { get; set; }
#endif
        /// <summary>The reply-to email address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SentFromReplyAddress { get; set; }
#nullable restore
#else
        public string SentFromReplyAddress { get; set; }
#endif
        /// <summary>When the email was sent, in ISO-8601 format. If omitted, the stored sent_time will be null.</summary>
        public DateTimeOffset? SentTime { get; set; }
        /// <summary>The email address the email was sent to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SentToAddress { get; set; }
#nullable restore
#else
        public string SentToAddress { get; set; }
#endif
        /// <summary>List of BCC email addresses</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? SentToBccAddressList { get; set; }
#nullable restore
#else
        public List<string> SentToBccAddressList { get; set; }
#endif
        /// <summary>List of CC email addresses</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? SentToCcAddressList { get; set; }
#nullable restore
#else
        public List<string> SentToCcAddressList { get; set; }
#endif
        /// <summary>The subject of the email</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Models.CreateEmailSentRequest"/> and sets the default values.
        /// </summary>
        public CreateEmailSentRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.CreateEmailSentRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Keap.OpenApiClient.Models.CreateEmailSentRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Keap.OpenApiClient.Models.CreateEmailSentRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "clicked_time", n => { ClickedTime = n.GetDateTimeOffsetValue(); } },
                { "contact_id", n => { ContactId = n.GetStringValue(); } },
                { "headers", n => { Headers = n.GetStringValue(); } },
                { "html_content", n => { HtmlContent = n.GetStringValue(); } },
                { "opened_time", n => { OpenedTime = n.GetDateTimeOffsetValue(); } },
                { "original_provider", n => { OriginalProvider = n.GetEnumValue<global::Soenneker.Keap.OpenApiClient.Models.CreateEmailSentRequestOriginalProvider>(); } },
                { "original_provider_id", n => { OriginalProviderId = n.GetStringValue(); } },
                { "plain_content", n => { PlainContent = n.GetStringValue(); } },
                { "provider_source_id", n => { ProviderSourceId = n.GetStringValue(); } },
                { "received_time", n => { ReceivedTime = n.GetDateTimeOffsetValue(); } },
                { "sent_from_address", n => { SentFromAddress = n.GetStringValue(); } },
                { "sent_from_reply_address", n => { SentFromReplyAddress = n.GetStringValue(); } },
                { "sent_time", n => { SentTime = n.GetDateTimeOffsetValue(); } },
                { "sent_to_address", n => { SentToAddress = n.GetStringValue(); } },
                { "sent_to_bcc_address_list", n => { SentToBccAddressList = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "sent_to_cc_address_list", n => { SentToCcAddressList = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("clicked_time", ClickedTime);
            writer.WriteStringValue("contact_id", ContactId);
            writer.WriteStringValue("headers", Headers);
            writer.WriteStringValue("html_content", HtmlContent);
            writer.WriteDateTimeOffsetValue("opened_time", OpenedTime);
            writer.WriteEnumValue<global::Soenneker.Keap.OpenApiClient.Models.CreateEmailSentRequestOriginalProvider>("original_provider", OriginalProvider);
            writer.WriteStringValue("original_provider_id", OriginalProviderId);
            writer.WriteStringValue("plain_content", PlainContent);
            writer.WriteStringValue("provider_source_id", ProviderSourceId);
            writer.WriteDateTimeOffsetValue("received_time", ReceivedTime);
            writer.WriteStringValue("sent_from_address", SentFromAddress);
            writer.WriteStringValue("sent_from_reply_address", SentFromReplyAddress);
            writer.WriteDateTimeOffsetValue("sent_time", SentTime);
            writer.WriteStringValue("sent_to_address", SentToAddress);
            writer.WriteCollectionOfPrimitiveValues<string>("sent_to_bcc_address_list", SentToBccAddressList);
            writer.WriteCollectionOfPrimitiveValues<string>("sent_to_cc_address_list", SentToCcAddressList);
            writer.WriteStringValue("subject", Subject);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
