// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    /// <summary>
    /// opportunity
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateOpportunityRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Affiliate ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AffiliateId { get; set; }
#nullable restore
#else
        public string AffiliateId { get; set; }
#endif
        /// <summary>Associated contact ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactId { get; set; }
#nullable restore
#else
        public string ContactId { get; set; }
#endif
        /// <summary>The custom_fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Keap.OpenApiClient.Models.CustomField>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Keap.OpenApiClient.Models.CustomField> CustomFields { get; set; }
#endif
        /// <summary>Estimated close timestamp (ISO-8601)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EstimatedCloseTime { get; set; }
#nullable restore
#else
        public string EstimatedCloseTime { get; set; }
#endif
        /// <summary>Include in sales forecast</summary>
        public bool? IncludeInForecast { get; set; }
        /// <summary>Notes for next action</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextActionNotes { get; set; }
#nullable restore
#else
        public string NextActionNotes { get; set; }
#endif
        /// <summary>Next action timestamp (ISO-8601)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextActionTime { get; set; }
#nullable restore
#else
        public string NextActionTime { get; set; }
#endif
        /// <summary>General notes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OpportunityNotes { get; set; }
#nullable restore
#else
        public string OpportunityNotes { get; set; }
#endif
        /// <summary>Opportunity title</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OpportunityTitle { get; set; }
#nullable restore
#else
        public string OpportunityTitle { get; set; }
#endif
        /// <summary>High revenue estimate</summary>
        public double? ProjectedRevenueHigh { get; set; }
        /// <summary>Low revenue estimate</summary>
        public double? ProjectedRevenueLow { get; set; }
        /// <summary>Pipeline stage ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StageId { get; set; }
#nullable restore
#else
        public string StageId { get; set; }
#endif
        /// <summary>Assigned user ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Models.CreateOpportunityRequest"/> and sets the default values.
        /// </summary>
        public CreateOpportunityRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.CreateOpportunityRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Keap.OpenApiClient.Models.CreateOpportunityRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Keap.OpenApiClient.Models.CreateOpportunityRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "affiliate_id", n => { AffiliateId = n.GetStringValue(); } },
                { "contact_id", n => { ContactId = n.GetStringValue(); } },
                { "custom_fields", n => { CustomFields = n.GetCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.CustomField>(global::Soenneker.Keap.OpenApiClient.Models.CustomField.CreateFromDiscriminatorValue)?.AsList(); } },
                { "estimated_close_time", n => { EstimatedCloseTime = n.GetStringValue(); } },
                { "include_in_forecast", n => { IncludeInForecast = n.GetBoolValue(); } },
                { "next_action_notes", n => { NextActionNotes = n.GetStringValue(); } },
                { "next_action_time", n => { NextActionTime = n.GetStringValue(); } },
                { "opportunity_notes", n => { OpportunityNotes = n.GetStringValue(); } },
                { "opportunity_title", n => { OpportunityTitle = n.GetStringValue(); } },
                { "projected_revenue_high", n => { ProjectedRevenueHigh = n.GetDoubleValue(); } },
                { "projected_revenue_low", n => { ProjectedRevenueLow = n.GetDoubleValue(); } },
                { "stage_id", n => { StageId = n.GetStringValue(); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("affiliate_id", AffiliateId);
            writer.WriteStringValue("contact_id", ContactId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.CustomField>("custom_fields", CustomFields);
            writer.WriteStringValue("estimated_close_time", EstimatedCloseTime);
            writer.WriteBoolValue("include_in_forecast", IncludeInForecast);
            writer.WriteStringValue("next_action_notes", NextActionNotes);
            writer.WriteStringValue("next_action_time", NextActionTime);
            writer.WriteStringValue("opportunity_notes", OpportunityNotes);
            writer.WriteStringValue("opportunity_title", OpportunityTitle);
            writer.WriteDoubleValue("projected_revenue_high", ProjectedRevenueHigh);
            writer.WriteDoubleValue("projected_revenue_low", ProjectedRevenueLow);
            writer.WriteStringValue("stage_id", StageId);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
