// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    /// <summary>Type of criteria: DATE_RANGE, PROMO_CODE, PRODUCT, SUBSCRIPTION_PLAN, or ORDER_TOTAL</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateShippingDiscountCriteriaBodyType
    {
        [EnumMember(Value = "DATE_RANGE")]
        #pragma warning disable CS1591
        DateRange,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROMO_CODE")]
        #pragma warning disable CS1591
        PromoCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRODUCT")]
        #pragma warning disable CS1591
        Product,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUBSCRIPTION_PLAN")]
        #pragma warning disable CS1591
        SubscriptionPlan,
        #pragma warning restore CS1591
        [EnumMember(Value = "ORDER_TOTAL")]
        #pragma warning disable CS1591
        OrderTotal,
        #pragma warning restore CS1591
    }
}
