// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CustomFieldGroupRecordType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "CONTACT")]
        #pragma warning disable CS1591
        Contact,
        #pragma warning restore CS1591
        [EnumMember(Value = "REFERRAL_PARTNER")]
        #pragma warning disable CS1591
        ReferralPartner,
        #pragma warning restore CS1591
        [EnumMember(Value = "OPPORTUNITY")]
        #pragma warning disable CS1591
        Opportunity,
        #pragma warning restore CS1591
        [EnumMember(Value = "TASK_NOTE_APPOINTMENT")]
        #pragma warning disable CS1591
        TaskNoteAppointment,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPANY")]
        #pragma warning disable CS1591
        Company,
        #pragma warning restore CS1591
        [EnumMember(Value = "ORDER")]
        #pragma warning disable CS1591
        Order,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUBSCRIPTION")]
        #pragma warning disable CS1591
        Subscription,
        #pragma warning restore CS1591
    }
}
