// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    /// <summary>Email address slot</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EmailAddressField
    {
        [EnumMember(Value = "EMAIL_FIELD_UNSPECIFIED")]
        #pragma warning disable CS1591
        EmailFieldUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "EMAIL1")]
        #pragma warning disable CS1591
        Email1,
        #pragma warning restore CS1591
        [EnumMember(Value = "EMAIL2")]
        #pragma warning disable CS1591
        Email2,
        #pragma warning restore CS1591
        [EnumMember(Value = "EMAIL3")]
        #pragma warning disable CS1591
        Email3,
        #pragma warning restore CS1591
    }
}
