// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    /// <summary>Fax number slot</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FaxNumberField
    {
        [EnumMember(Value = "FAX_NUMBER_FIELD_UNSPECIFIED")]
        #pragma warning disable CS1591
        FaxNumberFieldUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAX1")]
        #pragma warning disable CS1591
        Fax1,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAX2")]
        #pragma warning disable CS1591
        Fax2,
        #pragma warning restore CS1591
    }
}
