// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    /// <summary>File box type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FileMetadataFileBoxType
    {
        [EnumMember(Value = "APPLICATION")]
        #pragma warning disable CS1591
        Application,
        #pragma warning restore CS1591
        [EnumMember(Value = "IMAGE")]
        #pragma warning disable CS1591
        Image,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAX")]
        #pragma warning disable CS1591
        Fax,
        #pragma warning restore CS1591
        [EnumMember(Value = "ATTACHMENT")]
        #pragma warning disable CS1591
        Attachment,
        #pragma warning restore CS1591
        [EnumMember(Value = "TICKET")]
        #pragma warning disable CS1591
        Ticket,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONTACT")]
        #pragma warning disable CS1591
        Contact,
        #pragma warning restore CS1591
        [EnumMember(Value = "DIGITAL_PRODUCT")]
        #pragma warning disable CS1591
        DigitalProduct,
        #pragma warning restore CS1591
        [EnumMember(Value = "IMPORT")]
        #pragma warning disable CS1591
        Import,
        #pragma warning restore CS1591
        [EnumMember(Value = "HIDDEN")]
        #pragma warning disable CS1591
        Hidden,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEB_FORM")]
        #pragma warning disable CS1591
        WebForm,
        #pragma warning restore CS1591
        [EnumMember(Value = "STYLED_CART")]
        #pragma warning disable CS1591
        StyledCart,
        #pragma warning restore CS1591
        [EnumMember(Value = "RESAMPLED_IMAGE")]
        #pragma warning disable CS1591
        ResampledImage,
        #pragma warning restore CS1591
        [EnumMember(Value = "TEMPLATE_THUMBNAIL")]
        #pragma warning disable CS1591
        TemplateThumbnail,
        #pragma warning restore CS1591
        [EnumMember(Value = "FUNNEL")]
        #pragma warning disable CS1591
        Funnel,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOGO_THUMBNAIL")]
        #pragma warning disable CS1591
        LogoThumbnail,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNLAYER")]
        #pragma warning disable CS1591
        Unlayer,
        #pragma warning restore CS1591
        [EnumMember(Value = "BRANDING_CENTER_LOGO")]
        #pragma warning disable CS1591
        BrandingCenterLogo,
        #pragma warning restore CS1591
    }
}
