// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InvoiceOrderPayment : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The payment amount.</summary>
        public double? Amount { get; set; }
        /// <summary>The invoice order payment ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The invoice ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceId { get; set; }
#nullable restore
#else
        public string InvoiceId { get; set; }
#endif
        /// <summary>When this payment record was last updated.</summary>
        public DateTimeOffset? LastUpdatedTime { get; set; }
        /// <summary>A note about the payment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Note { get; set; }
#nullable restore
#else
        public string Note { get; set; }
#endif
        /// <summary>The payment ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentId { get; set; }
#nullable restore
#else
        public string PaymentId { get; set; }
#endif
        /// <summary>The payment status.</summary>
        public global::Soenneker.Keap.OpenApiClient.Models.InvoiceOrderPaymentPayStatus? PayStatus { get; set; }
        /// <summary>The date and time of payment.</summary>
        public DateTimeOffset? PayTime { get; set; }
        /// <summary>The refund invoice payment ID, if this is a refund.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RefundInvoicePaymentId { get; set; }
#nullable restore
#else
        public string RefundInvoicePaymentId { get; set; }
#endif
        /// <summary>Whether to skip commission for this payment.</summary>
        public bool? SkipCommission { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Models.InvoiceOrderPayment"/> and sets the default values.
        /// </summary>
        public InvoiceOrderPayment()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.InvoiceOrderPayment"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Keap.OpenApiClient.Models.InvoiceOrderPayment CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Keap.OpenApiClient.Models.InvoiceOrderPayment();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetDoubleValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "invoice_id", n => { InvoiceId = n.GetStringValue(); } },
                { "last_updated_time", n => { LastUpdatedTime = n.GetDateTimeOffsetValue(); } },
                { "note", n => { Note = n.GetStringValue(); } },
                { "pay_status", n => { PayStatus = n.GetEnumValue<global::Soenneker.Keap.OpenApiClient.Models.InvoiceOrderPaymentPayStatus>(); } },
                { "pay_time", n => { PayTime = n.GetDateTimeOffsetValue(); } },
                { "payment_id", n => { PaymentId = n.GetStringValue(); } },
                { "refund_invoice_payment_id", n => { RefundInvoicePaymentId = n.GetStringValue(); } },
                { "skip_commission", n => { SkipCommission = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("amount", Amount);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("invoice_id", InvoiceId);
            writer.WriteDateTimeOffsetValue("last_updated_time", LastUpdatedTime);
            writer.WriteStringValue("note", Note);
            writer.WriteStringValue("payment_id", PaymentId);
            writer.WriteEnumValue<global::Soenneker.Keap.OpenApiClient.Models.InvoiceOrderPaymentPayStatus>("pay_status", PayStatus);
            writer.WriteDateTimeOffsetValue("pay_time", PayTime);
            writer.WriteStringValue("refund_invoice_payment_id", RefundInvoicePaymentId);
            writer.WriteBoolValue("skip_commission", SkipCommission);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
