// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    /// <summary>The payment status.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InvoiceOrderPaymentPayStatus
    {
        [EnumMember(Value = "MANUAL_PAID")]
        #pragma warning disable CS1591
        ManualPaid,
        #pragma warning restore CS1591
        [EnumMember(Value = "REFUNDED")]
        #pragma warning disable CS1591
        Refunded,
        #pragma warning restore CS1591
        [EnumMember(Value = "VOIDED")]
        #pragma warning disable CS1591
        Voided,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAYPAL_PAID")]
        #pragma warning disable CS1591
        PaypalPaid,
        #pragma warning restore CS1591
        [EnumMember(Value = "APPROVED")]
        #pragma warning disable CS1591
        Approved,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAILED")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
    }
}
