// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LeadSourceExpense : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The amount of the expense</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue? Amount { get; set; }
#nullable restore
#else
        public global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue Amount { get; set; }
#endif
        /// <summary>The date the expense was created</summary>
        public DateTimeOffset? CreateTime { get; set; }
        /// <summary>The unique identifier for the expense.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The date the expense was incurred</summary>
        public DateTimeOffset? IncurredTime { get; set; }
        /// <summary>The ID of the lead source this expense belongs to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeadSourceId { get; set; }
#nullable restore
#else
        public string LeadSourceId { get; set; }
#endif
        /// <summary>If this expense was incurred from a recurring expense, this is the ID of that recurring expense</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeadSourceRecurringExpenseId { get; set; }
#nullable restore
#else
        public string LeadSourceRecurringExpenseId { get; set; }
#endif
        /// <summary>The notes for the expense</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>The title of the expense</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The date the expense was last updated</summary>
        public DateTimeOffset? UpdateTime { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Models.LeadSourceExpense"/> and sets the default values.
        /// </summary>
        public LeadSourceExpense()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.LeadSourceExpense"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Keap.OpenApiClient.Models.LeadSourceExpense CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Keap.OpenApiClient.Models.LeadSourceExpense();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetObjectValue<global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue>(global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue.CreateFromDiscriminatorValue); } },
                { "create_time", n => { CreateTime = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "incurred_time", n => { IncurredTime = n.GetDateTimeOffsetValue(); } },
                { "lead_source_id", n => { LeadSourceId = n.GetStringValue(); } },
                { "lead_source_recurring_expense_id", n => { LeadSourceRecurringExpenseId = n.GetStringValue(); } },
                { "notes", n => { Notes = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "update_time", n => { UpdateTime = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue>("amount", Amount);
            writer.WriteDateTimeOffsetValue("create_time", CreateTime);
            writer.WriteStringValue("id", Id);
            writer.WriteDateTimeOffsetValue("incurred_time", IncurredTime);
            writer.WriteStringValue("lead_source_id", LeadSourceId);
            writer.WriteStringValue("lead_source_recurring_expense_id", LeadSourceRecurringExpenseId);
            writer.WriteStringValue("notes", Notes);
            writer.WriteStringValue("title", Title);
            writer.WriteDateTimeOffsetValue("update_time", UpdateTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
