// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListMerchantsResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The default_merchant_account_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultMerchantAccountId { get; set; }
#nullable restore
#else
        public string DefaultMerchantAccountId { get; set; }
#endif
        /// <summary>The merchant_accounts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Keap.OpenApiClient.Models.ListMerchantAccountResponse>? MerchantAccounts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Keap.OpenApiClient.Models.ListMerchantAccountResponse> MerchantAccounts { get; set; }
#endif
        /// <summary>The next_page_token property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextPageToken { get; set; }
#nullable restore
#else
        public string NextPageToken { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Models.ListMerchantsResponse"/> and sets the default values.
        /// </summary>
        public ListMerchantsResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.ListMerchantsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Keap.OpenApiClient.Models.ListMerchantsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Keap.OpenApiClient.Models.ListMerchantsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "default_merchant_account_id", n => { DefaultMerchantAccountId = n.GetStringValue(); } },
                { "merchant_accounts", n => { MerchantAccounts = n.GetCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.ListMerchantAccountResponse>(global::Soenneker.Keap.OpenApiClient.Models.ListMerchantAccountResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "next_page_token", n => { NextPageToken = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("default_merchant_account_id", DefaultMerchantAccountId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.ListMerchantAccountResponse>("merchant_accounts", MerchantAccounts);
            writer.WriteStringValue("next_page_token", NextPageToken);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
