// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OrderV2 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether or not card-related payments should be allowed on this order. Applies only to Keap Pro/Max edition.</summary>
        public bool? AllowPayment { get; set; }
        /// <summary>Whether or not PayPal payments should be allowed on this order. Applies only to Keap Pro/Max edition.</summary>
        public bool? AllowPaypal { get; set; }
        /// <summary>Contact associated with this order</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Keap.OpenApiClient.Models.BasicContact? Contact { get; set; }
#nullable restore
#else
        public global::Soenneker.Keap.OpenApiClient.Models.BasicContact Contact { get; set; }
#endif
        /// <summary>When this order was originally created. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z)</summary>
        public DateTimeOffset? CreationTime { get; set; }
        /// <summary>Credit status of the order</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreditStatus { get; set; }
#nullable restore
#else
        public string CreditStatus { get; set; }
#endif
        /// <summary>List of custom field values applied to this order</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Keap.OpenApiClient.Models.CustomFieldValue>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Keap.OpenApiClient.Models.CustomFieldValue> CustomFields { get; set; }
#endif
        /// <summary>The date and time the invoice is due. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z)</summary>
        public DateTimeOffset? DueTime { get; set; }
        /// <summary>The date and time the order was created in the external system. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z)</summary>
        public DateTimeOffset? ExternalCreateTime { get; set; }
        /// <summary>The external system user that created this order.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalCreateUser { get; set; }
#nullable restore
#else
        public string ExternalCreateUser { get; set; }
#endif
        /// <summary>The date and time the order was last updated in the external system. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z)</summary>
        public DateTimeOffset? ExternalUpdateTime { get; set; }
        /// <summary>A list of attached files to this order. Applies only to Keap Pro/Max edition.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Keap.OpenApiClient.Models.InvoiceFile>? Files { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Keap.OpenApiClient.Models.InvoiceFile> Files { get; set; }
#endif
        /// <summary>Unique identifier for the order</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Associated invoice ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceId { get; set; }
#nullable restore
#else
        public string InvoiceId { get; set; }
#endif
        /// <summary>The associated invoice identifier. Applies only to Keap Pro/Max edition. Feature not yet supported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceNumber { get; set; }
#nullable restore
#else
        public string InvoiceNumber { get; set; }
#endif
        /// <summary>ID of the lead affiliate</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeadAffiliateId { get; set; }
#nullable restore
#else
        public string LeadAffiliateId { get; set; }
#endif
        /// <summary>When this order was changed. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z)</summary>
        public DateTimeOffset? ModificationTime { get; set; }
        /// <summary>Internal notes for the order</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>List of items in the order</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Keap.OpenApiClient.Models.OrderItem>? OrderItems { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Keap.OpenApiClient.Models.OrderItem> OrderItems { get; set; }
#endif
        /// <summary>A user-defined date and time of the order. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z)</summary>
        public DateTimeOffset? OrderTime { get; set; }
        /// <summary>The order type.</summary>
        public global::Soenneker.Keap.OpenApiClient.Models.OrderV2OrderType? OrderType { get; set; }
        /// <summary>Payment plan details if applicable</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Keap.OpenApiClient.Models.PaymentPlan? PaymentPlan { get; set; }
#nullable restore
#else
        public global::Soenneker.Keap.OpenApiClient.Models.PaymentPlan PaymentPlan { get; set; }
#endif
        /// <summary>Promotional code applied</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PromoCode { get; set; }
#nullable restore
#else
        public string PromoCode { get; set; }
#endif
        /// <summary>Refund status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RefundStatus { get; set; }
#nullable restore
#else
        public string RefundStatus { get; set; }
#endif
        /// <summary>Total amount refunded</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue? RefundTotal { get; set; }
#nullable restore
#else
        public global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue RefundTotal { get; set; }
#endif
        /// <summary>ID of the sales affiliate</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SalesAffiliateId { get; set; }
#nullable restore
#else
        public string SalesAffiliateId { get; set; }
#endif
        /// <summary>The date and time the invoice was sent. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z)</summary>
        public DateTimeOffset? SentTime { get; set; }
        /// <summary>Shipping details for the order</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Keap.OpenApiClient.Models.ShippingInformation? ShippingInformation { get; set; }
#nullable restore
#else
        public global::Soenneker.Keap.OpenApiClient.Models.ShippingInformation ShippingInformation { get; set; }
#endif
        /// <summary>The source where the order was created.</summary>
        public global::Soenneker.Keap.OpenApiClient.Models.OrderV2SourceType? SourceType { get; set; }
        /// <summary>The order status.</summary>
        public global::Soenneker.Keap.OpenApiClient.Models.OrderV2Status? Status { get; set; }
        /// <summary>Whether order is synced with external systems</summary>
        public bool? Synced { get; set; }
        /// <summary>Order terms and conditions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Terms { get; set; }
#nullable restore
#else
        public string Terms { get; set; }
#endif
        /// <summary>Title of the order</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The total amount of the order.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue? Total { get; set; }
#nullable restore
#else
        public global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue Total { get; set; }
#endif
        /// <summary>The total amount of the order that is due. This is not current balance.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue? TotalDue { get; set; }
#nullable restore
#else
        public global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue TotalDue { get; set; }
#endif
        /// <summary>The total amount paid to the order.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue? TotalPaid { get; set; }
#nullable restore
#else
        public global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue TotalPaid { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Models.OrderV2"/> and sets the default values.
        /// </summary>
        public OrderV2()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.OrderV2"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Keap.OpenApiClient.Models.OrderV2 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Keap.OpenApiClient.Models.OrderV2();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allow_payment", n => { AllowPayment = n.GetBoolValue(); } },
                { "allow_paypal", n => { AllowPaypal = n.GetBoolValue(); } },
                { "contact", n => { Contact = n.GetObjectValue<global::Soenneker.Keap.OpenApiClient.Models.BasicContact>(global::Soenneker.Keap.OpenApiClient.Models.BasicContact.CreateFromDiscriminatorValue); } },
                { "creation_time", n => { CreationTime = n.GetDateTimeOffsetValue(); } },
                { "credit_status", n => { CreditStatus = n.GetStringValue(); } },
                { "custom_fields", n => { CustomFields = n.GetCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.CustomFieldValue>(global::Soenneker.Keap.OpenApiClient.Models.CustomFieldValue.CreateFromDiscriminatorValue)?.AsList(); } },
                { "due_time", n => { DueTime = n.GetDateTimeOffsetValue(); } },
                { "external_create_time", n => { ExternalCreateTime = n.GetDateTimeOffsetValue(); } },
                { "external_create_user", n => { ExternalCreateUser = n.GetStringValue(); } },
                { "external_update_time", n => { ExternalUpdateTime = n.GetDateTimeOffsetValue(); } },
                { "files", n => { Files = n.GetCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.InvoiceFile>(global::Soenneker.Keap.OpenApiClient.Models.InvoiceFile.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "invoice_id", n => { InvoiceId = n.GetStringValue(); } },
                { "invoice_number", n => { InvoiceNumber = n.GetStringValue(); } },
                { "lead_affiliate_id", n => { LeadAffiliateId = n.GetStringValue(); } },
                { "modification_time", n => { ModificationTime = n.GetDateTimeOffsetValue(); } },
                { "notes", n => { Notes = n.GetStringValue(); } },
                { "order_items", n => { OrderItems = n.GetCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.OrderItem>(global::Soenneker.Keap.OpenApiClient.Models.OrderItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "order_time", n => { OrderTime = n.GetDateTimeOffsetValue(); } },
                { "order_type", n => { OrderType = n.GetEnumValue<global::Soenneker.Keap.OpenApiClient.Models.OrderV2OrderType>(); } },
                { "payment_plan", n => { PaymentPlan = n.GetObjectValue<global::Soenneker.Keap.OpenApiClient.Models.PaymentPlan>(global::Soenneker.Keap.OpenApiClient.Models.PaymentPlan.CreateFromDiscriminatorValue); } },
                { "promo_code", n => { PromoCode = n.GetStringValue(); } },
                { "refund_status", n => { RefundStatus = n.GetStringValue(); } },
                { "refund_total", n => { RefundTotal = n.GetObjectValue<global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue>(global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue.CreateFromDiscriminatorValue); } },
                { "sales_affiliate_id", n => { SalesAffiliateId = n.GetStringValue(); } },
                { "sent_time", n => { SentTime = n.GetDateTimeOffsetValue(); } },
                { "shipping_information", n => { ShippingInformation = n.GetObjectValue<global::Soenneker.Keap.OpenApiClient.Models.ShippingInformation>(global::Soenneker.Keap.OpenApiClient.Models.ShippingInformation.CreateFromDiscriminatorValue); } },
                { "source_type", n => { SourceType = n.GetEnumValue<global::Soenneker.Keap.OpenApiClient.Models.OrderV2SourceType>(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Keap.OpenApiClient.Models.OrderV2Status>(); } },
                { "synced", n => { Synced = n.GetBoolValue(); } },
                { "terms", n => { Terms = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "total", n => { Total = n.GetObjectValue<global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue>(global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue.CreateFromDiscriminatorValue); } },
                { "total_due", n => { TotalDue = n.GetObjectValue<global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue>(global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue.CreateFromDiscriminatorValue); } },
                { "total_paid", n => { TotalPaid = n.GetObjectValue<global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue>(global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allow_payment", AllowPayment);
            writer.WriteBoolValue("allow_paypal", AllowPaypal);
            writer.WriteObjectValue<global::Soenneker.Keap.OpenApiClient.Models.BasicContact>("contact", Contact);
            writer.WriteDateTimeOffsetValue("creation_time", CreationTime);
            writer.WriteStringValue("credit_status", CreditStatus);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.CustomFieldValue>("custom_fields", CustomFields);
            writer.WriteDateTimeOffsetValue("due_time", DueTime);
            writer.WriteDateTimeOffsetValue("external_create_time", ExternalCreateTime);
            writer.WriteStringValue("external_create_user", ExternalCreateUser);
            writer.WriteDateTimeOffsetValue("external_update_time", ExternalUpdateTime);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.InvoiceFile>("files", Files);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("invoice_id", InvoiceId);
            writer.WriteStringValue("invoice_number", InvoiceNumber);
            writer.WriteStringValue("lead_affiliate_id", LeadAffiliateId);
            writer.WriteDateTimeOffsetValue("modification_time", ModificationTime);
            writer.WriteStringValue("notes", Notes);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.OrderItem>("order_items", OrderItems);
            writer.WriteDateTimeOffsetValue("order_time", OrderTime);
            writer.WriteEnumValue<global::Soenneker.Keap.OpenApiClient.Models.OrderV2OrderType>("order_type", OrderType);
            writer.WriteObjectValue<global::Soenneker.Keap.OpenApiClient.Models.PaymentPlan>("payment_plan", PaymentPlan);
            writer.WriteStringValue("promo_code", PromoCode);
            writer.WriteStringValue("refund_status", RefundStatus);
            writer.WriteObjectValue<global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue>("refund_total", RefundTotal);
            writer.WriteStringValue("sales_affiliate_id", SalesAffiliateId);
            writer.WriteDateTimeOffsetValue("sent_time", SentTime);
            writer.WriteObjectValue<global::Soenneker.Keap.OpenApiClient.Models.ShippingInformation>("shipping_information", ShippingInformation);
            writer.WriteEnumValue<global::Soenneker.Keap.OpenApiClient.Models.OrderV2SourceType>("source_type", SourceType);
            writer.WriteEnumValue<global::Soenneker.Keap.OpenApiClient.Models.OrderV2Status>("status", Status);
            writer.WriteBoolValue("synced", Synced);
            writer.WriteStringValue("terms", Terms);
            writer.WriteStringValue("title", Title);
            writer.WriteObjectValue<global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue>("total", Total);
            writer.WriteObjectValue<global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue>("total_due", TotalDue);
            writer.WriteObjectValue<global::Soenneker.Keap.OpenApiClient.Models.CurrencyValue>("total_paid", TotalPaid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
