// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    /// <summary>The status of the payment plan item. Possible values are:- `UNPAID_MANUAL` - The item is set for manual charge, and its `amount_due` has not been completely paid.- `UNPAID_AUTOCHARGE` - The item is set for auto-charge, and its `amount_due` has not been completely paid.- `PAID` - The item has been completely paid.- `FAILED` - The item `amount_due` has not been completely paid, and there was a failure. (*Note: This status is deprecated and not currently used.*)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PaymentPlanItemStatus
    {
        [EnumMember(Value = "UNPAID_MANUAL")]
        #pragma warning disable CS1591
        UnpaidManual,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNPAID_AUTOCHARGE")]
        #pragma warning disable CS1591
        UnpaidAutocharge,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAID")]
        #pragma warning disable CS1591
        Paid,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAILED")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
    }
}
