// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PaymentMethod : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>If present, it provides additional details for payment methods of payment_method_type CARD.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Keap.OpenApiClient.Models.CardInfo? CardInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Keap.OpenApiClient.Models.CardInfo CardInfo { get; set; }
#endif
        /// <summary>The id of the contact the payment method is associated with.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactId { get; set; }
#nullable restore
#else
        public string ContactId { get; set; }
#endif
        /// <summary>When this payment method was made. In ISO-8601 format.</summary>
        public DateTimeOffset? CreatedTime { get; set; }
        /// <summary>For backward-compatibility with v1 endpoints. If present, it&apos;s the credit card id this payment method refers to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreditCardId { get; set; }
#nullable restore
#else
        public string CreditCardId { get; set; }
#endif
        /// <summary>The merchant account id through which the payment method was tokenize.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MerchantAccountId { get; set; }
#nullable restore
#else
        public string MerchantAccountId { get; set; }
#endif
        /// <summary>The merchant account type through which the payment method was tokenized.</summary>
        public global::Soenneker.Keap.OpenApiClient.Models.PaymentMethodMerchantAccountType? MerchantAccountType { get; set; }
        /// <summary>The unique identifier of the payment method.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentMethodId { get; set; }
#nullable restore
#else
        public string PaymentMethodId { get; set; }
#endif
        /// <summary>The type of payment method. For now, only CARD is supported.</summary>
        public global::Soenneker.Keap.OpenApiClient.Models.CardPaymentMethodType? PaymentMethodType { get; set; }
        /// <summary>Status of the payment method. Fow now, only EXPIRED is supported.</summary>
        public global::Soenneker.Keap.OpenApiClient.Models.ExpiredStatus? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Models.PaymentMethod"/> and sets the default values.
        /// </summary>
        public PaymentMethod()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.PaymentMethod"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Keap.OpenApiClient.Models.PaymentMethod CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Keap.OpenApiClient.Models.PaymentMethod();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "card_info", n => { CardInfo = n.GetObjectValue<global::Soenneker.Keap.OpenApiClient.Models.CardInfo>(global::Soenneker.Keap.OpenApiClient.Models.CardInfo.CreateFromDiscriminatorValue); } },
                { "contact_id", n => { ContactId = n.GetStringValue(); } },
                { "created_time", n => { CreatedTime = n.GetDateTimeOffsetValue(); } },
                { "credit_card_id", n => { CreditCardId = n.GetStringValue(); } },
                { "merchant_account_id", n => { MerchantAccountId = n.GetStringValue(); } },
                { "merchant_account_type", n => { MerchantAccountType = n.GetEnumValue<global::Soenneker.Keap.OpenApiClient.Models.PaymentMethodMerchantAccountType>(); } },
                { "payment_method_id", n => { PaymentMethodId = n.GetStringValue(); } },
                { "payment_method_type", n => { PaymentMethodType = n.GetEnumValue<global::Soenneker.Keap.OpenApiClient.Models.CardPaymentMethodType>(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Keap.OpenApiClient.Models.ExpiredStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Keap.OpenApiClient.Models.CardInfo>("card_info", CardInfo);
            writer.WriteStringValue("contact_id", ContactId);
            writer.WriteDateTimeOffsetValue("created_time", CreatedTime);
            writer.WriteStringValue("credit_card_id", CreditCardId);
            writer.WriteStringValue("merchant_account_id", MerchantAccountId);
            writer.WriteEnumValue<global::Soenneker.Keap.OpenApiClient.Models.PaymentMethodMerchantAccountType>("merchant_account_type", MerchantAccountType);
            writer.WriteStringValue("payment_method_id", PaymentMethodId);
            writer.WriteEnumValue<global::Soenneker.Keap.OpenApiClient.Models.CardPaymentMethodType>("payment_method_type", PaymentMethodType);
            writer.WriteEnumValue<global::Soenneker.Keap.OpenApiClient.Models.ExpiredStatus>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
