// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProductCommission : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Level 1 fixed dollar amount to be paid for commission. This will be set for the Sale. This is deprecated for `level_1`</summary>
        public double? DollarAmount { get; set; }
        /// <summary>Payout rules for Level 1 recipients of the commission.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Keap.OpenApiClient.Models.CommissionItem? Level1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Keap.OpenApiClient.Models.CommissionItem Level1 { get; set; }
#endif
        /// <summary>Payout rules for Level 2 recipients of the commission.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Keap.OpenApiClient.Models.CommissionItem? Level2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Keap.OpenApiClient.Models.CommissionItem Level2 { get; set; }
#endif
        /// <summary>The payout type for this commission.</summary>
        public global::Soenneker.Keap.OpenApiClient.Models.ProductCommissionPayoutType? PayoutType { get; set; }
        /// <summary>Level 1 percentage to be paid for commission (0-100). This will be set for the Sale. This is deprecated for `level_1`</summary>
        public double? Percentage { get; set; }
        /// <summary>Product ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductId { get; set; }
#nullable restore
#else
        public string ProductId { get; set; }
#endif
        /// <summary>Product name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductName { get; set; }
#nullable restore
#else
        public string ProductName { get; set; }
#endif
        /// <summary>Product price</summary>
        public double? ProductPrice { get; set; }
        /// <summary>Payout rules for any unused commissions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Keap.OpenApiClient.Models.CommissionItem? Unused { get; set; }
#nullable restore
#else
        public global::Soenneker.Keap.OpenApiClient.Models.CommissionItem Unused { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Models.ProductCommission"/> and sets the default values.
        /// </summary>
        public ProductCommission()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.ProductCommission"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Keap.OpenApiClient.Models.ProductCommission CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Keap.OpenApiClient.Models.ProductCommission();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dollar_amount", n => { DollarAmount = n.GetDoubleValue(); } },
                { "level_1", n => { Level1 = n.GetObjectValue<global::Soenneker.Keap.OpenApiClient.Models.CommissionItem>(global::Soenneker.Keap.OpenApiClient.Models.CommissionItem.CreateFromDiscriminatorValue); } },
                { "level_2", n => { Level2 = n.GetObjectValue<global::Soenneker.Keap.OpenApiClient.Models.CommissionItem>(global::Soenneker.Keap.OpenApiClient.Models.CommissionItem.CreateFromDiscriminatorValue); } },
                { "payout_type", n => { PayoutType = n.GetEnumValue<global::Soenneker.Keap.OpenApiClient.Models.ProductCommissionPayoutType>(); } },
                { "percentage", n => { Percentage = n.GetDoubleValue(); } },
                { "product_id", n => { ProductId = n.GetStringValue(); } },
                { "product_name", n => { ProductName = n.GetStringValue(); } },
                { "product_price", n => { ProductPrice = n.GetDoubleValue(); } },
                { "unused", n => { Unused = n.GetObjectValue<global::Soenneker.Keap.OpenApiClient.Models.CommissionItem>(global::Soenneker.Keap.OpenApiClient.Models.CommissionItem.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("dollar_amount", DollarAmount);
            writer.WriteObjectValue<global::Soenneker.Keap.OpenApiClient.Models.CommissionItem>("level_1", Level1);
            writer.WriteObjectValue<global::Soenneker.Keap.OpenApiClient.Models.CommissionItem>("level_2", Level2);
            writer.WriteEnumValue<global::Soenneker.Keap.OpenApiClient.Models.ProductCommissionPayoutType>("payout_type", PayoutType);
            writer.WriteDoubleValue("percentage", Percentage);
            writer.WriteStringValue("product_id", ProductId);
            writer.WriteStringValue("product_name", ProductName);
            writer.WriteDoubleValue("product_price", ProductPrice);
            writer.WriteObjectValue<global::Soenneker.Keap.OpenApiClient.Models.CommissionItem>("unused", Unused);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
