// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RestV2Opportunity : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Affiliate ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AffiliateId { get; set; }
#nullable restore
#else
        public string AffiliateId { get; set; }
#endif
        /// <summary>The contact property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Keap.OpenApiClient.Models.OpportunityContact? Contact { get; set; }
#nullable restore
#else
        public global::Soenneker.Keap.OpenApiClient.Models.OpportunityContact Contact { get; set; }
#endif
        /// <summary>User who created the opportunity record</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>Creation timestamp (ISO-8601)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedTime { get; set; }
#nullable restore
#else
        public string CreatedTime { get; set; }
#endif
        /// <summary>The custom_fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Keap.OpenApiClient.Models.CustomField>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Keap.OpenApiClient.Models.CustomField> CustomFields { get; set; }
#endif
        /// <summary>Estimated close timestamp (ISO-8601)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EstimatedCloseTime { get; set; }
#nullable restore
#else
        public string EstimatedCloseTime { get; set; }
#endif
        /// <summary>Opportunity ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Include in sales forecast</summary>
        public bool? IncludeInForecast { get; set; }
        /// <summary>User who last updated the opportunity record</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastUpdatedBy { get; set; }
#nullable restore
#else
        public string LastUpdatedBy { get; set; }
#endif
        /// <summary>Last update timestamp (ISO-8601)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastUpdatedTime { get; set; }
#nullable restore
#else
        public string LastUpdatedTime { get; set; }
#endif
        /// <summary>Lead source</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeadSource { get; set; }
#nullable restore
#else
        public string LeadSource { get; set; }
#endif
        /// <summary>Monthly recurring revenue</summary>
        public double? MonthlyRevenue { get; set; }
        /// <summary>Notes for next action</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextActionNotes { get; set; }
#nullable restore
#else
        public string NextActionNotes { get; set; }
#endif
        /// <summary>Next action timestamp (ISO-8601)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextActionTime { get; set; }
#nullable restore
#else
        public string NextActionTime { get; set; }
#endif
        /// <summary>Objection reason</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Objection { get; set; }
#nullable restore
#else
        public string Objection { get; set; }
#endif
        /// <summary>General notes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OpportunityNotes { get; set; }
#nullable restore
#else
        public string OpportunityNotes { get; set; }
#endif
        /// <summary>Opportunity title</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OpportunityTitle { get; set; }
#nullable restore
#else
        public string OpportunityTitle { get; set; }
#endif
        /// <summary>Order revenue</summary>
        public double? OrderRevenue { get; set; }
        /// <summary>High revenue estimate</summary>
        public double? ProjectedRevenueHigh { get; set; }
        /// <summary>Low revenue estimate</summary>
        public double? ProjectedRevenueLow { get; set; }
        /// <summary>The stage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Keap.OpenApiClient.Models.OpportunityStage? Stage { get; set; }
#nullable restore
#else
        public global::Soenneker.Keap.OpenApiClient.Models.OpportunityStage Stage { get; set; }
#endif
        /// <summary>Timestamp when the opportunity entered its current stage (ISO-8601)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StageEntranceTime { get; set; }
#nullable restore
#else
        public string StageEntranceTime { get; set; }
#endif
        /// <summary>Status name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>Status ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusId { get; set; }
#nullable restore
#else
        public string StatusId { get; set; }
#endif
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Keap.OpenApiClient.Models.RestV2User? User { get; set; }
#nullable restore
#else
        public global::Soenneker.Keap.OpenApiClient.Models.RestV2User User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Models.RestV2Opportunity"/> and sets the default values.
        /// </summary>
        public RestV2Opportunity()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.RestV2Opportunity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Keap.OpenApiClient.Models.RestV2Opportunity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Keap.OpenApiClient.Models.RestV2Opportunity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "affiliate_id", n => { AffiliateId = n.GetStringValue(); } },
                { "contact", n => { Contact = n.GetObjectValue<global::Soenneker.Keap.OpenApiClient.Models.OpportunityContact>(global::Soenneker.Keap.OpenApiClient.Models.OpportunityContact.CreateFromDiscriminatorValue); } },
                { "created_by", n => { CreatedBy = n.GetStringValue(); } },
                { "created_time", n => { CreatedTime = n.GetStringValue(); } },
                { "custom_fields", n => { CustomFields = n.GetCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.CustomField>(global::Soenneker.Keap.OpenApiClient.Models.CustomField.CreateFromDiscriminatorValue)?.AsList(); } },
                { "estimated_close_time", n => { EstimatedCloseTime = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "include_in_forecast", n => { IncludeInForecast = n.GetBoolValue(); } },
                { "last_updated_by", n => { LastUpdatedBy = n.GetStringValue(); } },
                { "last_updated_time", n => { LastUpdatedTime = n.GetStringValue(); } },
                { "lead_source", n => { LeadSource = n.GetStringValue(); } },
                { "monthly_revenue", n => { MonthlyRevenue = n.GetDoubleValue(); } },
                { "next_action_notes", n => { NextActionNotes = n.GetStringValue(); } },
                { "next_action_time", n => { NextActionTime = n.GetStringValue(); } },
                { "objection", n => { Objection = n.GetStringValue(); } },
                { "opportunity_notes", n => { OpportunityNotes = n.GetStringValue(); } },
                { "opportunity_title", n => { OpportunityTitle = n.GetStringValue(); } },
                { "order_revenue", n => { OrderRevenue = n.GetDoubleValue(); } },
                { "projected_revenue_high", n => { ProjectedRevenueHigh = n.GetDoubleValue(); } },
                { "projected_revenue_low", n => { ProjectedRevenueLow = n.GetDoubleValue(); } },
                { "stage", n => { Stage = n.GetObjectValue<global::Soenneker.Keap.OpenApiClient.Models.OpportunityStage>(global::Soenneker.Keap.OpenApiClient.Models.OpportunityStage.CreateFromDiscriminatorValue); } },
                { "stage_entrance_time", n => { StageEntranceTime = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "status_id", n => { StatusId = n.GetStringValue(); } },
                { "user", n => { User = n.GetObjectValue<global::Soenneker.Keap.OpenApiClient.Models.RestV2User>(global::Soenneker.Keap.OpenApiClient.Models.RestV2User.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("affiliate_id", AffiliateId);
            writer.WriteObjectValue<global::Soenneker.Keap.OpenApiClient.Models.OpportunityContact>("contact", Contact);
            writer.WriteStringValue("created_by", CreatedBy);
            writer.WriteStringValue("created_time", CreatedTime);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.CustomField>("custom_fields", CustomFields);
            writer.WriteStringValue("estimated_close_time", EstimatedCloseTime);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("include_in_forecast", IncludeInForecast);
            writer.WriteStringValue("last_updated_by", LastUpdatedBy);
            writer.WriteStringValue("last_updated_time", LastUpdatedTime);
            writer.WriteStringValue("lead_source", LeadSource);
            writer.WriteDoubleValue("monthly_revenue", MonthlyRevenue);
            writer.WriteStringValue("next_action_notes", NextActionNotes);
            writer.WriteStringValue("next_action_time", NextActionTime);
            writer.WriteStringValue("objection", Objection);
            writer.WriteStringValue("opportunity_notes", OpportunityNotes);
            writer.WriteStringValue("opportunity_title", OpportunityTitle);
            writer.WriteDoubleValue("order_revenue", OrderRevenue);
            writer.WriteDoubleValue("projected_revenue_high", ProjectedRevenueHigh);
            writer.WriteDoubleValue("projected_revenue_low", ProjectedRevenueLow);
            writer.WriteObjectValue<global::Soenneker.Keap.OpenApiClient.Models.OpportunityStage>("stage", Stage);
            writer.WriteStringValue("stage_entrance_time", StageEntranceTime);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("status_id", StatusId);
            writer.WriteObjectValue<global::Soenneker.Keap.OpenApiClient.Models.RestV2User>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
