// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    /// <summary>The order type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RestCreateOrderRequestOrderType
    {
        [EnumMember(Value = "ONLINE")]
        #pragma warning disable CS1591
        Online,
        #pragma warning restore CS1591
        [EnumMember(Value = "OFFLINE")]
        #pragma warning disable CS1591
        Offline,
        #pragma warning restore CS1591
    }
}
