// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RestCreatePaymentRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether to apply this payment to commissions.</summary>
        public bool? ApplyToCommissions { get; set; }
        /// <summary>The external creation timestamp of this payment. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z)</summary>
        public DateTimeOffset? ExternalCreateTime { get; set; }
        /// <summary>The user who created this payment externally.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalCreateUser { get; set; }
#nullable restore
#else
        public string ExternalCreateUser { get; set; }
#endif
        /// <summary>The external source type of this payment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalSource { get; set; }
#nullable restore
#else
        public string ExternalSource { get; set; }
#endif
        /// <summary>The external source value of this payment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalSourceValue { get; set; }
#nullable restore
#else
        public string ExternalSourceValue { get; set; }
#endif
        /// <summary>The external status value of this payment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalStatusValue { get; set; }
#nullable restore
#else
        public string ExternalStatusValue { get; set; }
#endif
        /// <summary>The external update timestamp of this payment. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z)</summary>
        public DateTimeOffset? ExternalUpdateTime { get; set; }
        /// <summary>The notes for this payment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>The amount to pay. Must not exceed the current balance of the order. Must be greater than 0 if charging with a payment_method_id</summary>
        public double? PaymentAmount { get; set; }
        /// <summary>The payment method id to charge immediately against this order. Omit if you want to add a payment record instead.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentMethodId { get; set; }
#nullable restore
#else
        public string PaymentMethodId { get; set; }
#endif
        /// <summary>The manual payment method type for manually recording a payment. Value must match against the list of types defined under your application&apos;s Order Settings. Ignored if payment_method_id is provided.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentMethodType { get; set; }
#nullable restore
#else
        public string PaymentMethodType { get; set; }
#endif
        /// <summary>The date and time of payment. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z)</summary>
        public DateTimeOffset? PaymentTime { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Models.RestCreatePaymentRequest"/> and sets the default values.
        /// </summary>
        public RestCreatePaymentRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.RestCreatePaymentRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Keap.OpenApiClient.Models.RestCreatePaymentRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Keap.OpenApiClient.Models.RestCreatePaymentRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "apply_to_commissions", n => { ApplyToCommissions = n.GetBoolValue(); } },
                { "external_create_time", n => { ExternalCreateTime = n.GetDateTimeOffsetValue(); } },
                { "external_create_user", n => { ExternalCreateUser = n.GetStringValue(); } },
                { "external_source", n => { ExternalSource = n.GetStringValue(); } },
                { "external_source_value", n => { ExternalSourceValue = n.GetStringValue(); } },
                { "external_status_value", n => { ExternalStatusValue = n.GetStringValue(); } },
                { "external_update_time", n => { ExternalUpdateTime = n.GetDateTimeOffsetValue(); } },
                { "notes", n => { Notes = n.GetStringValue(); } },
                { "payment_amount", n => { PaymentAmount = n.GetDoubleValue(); } },
                { "payment_method_id", n => { PaymentMethodId = n.GetStringValue(); } },
                { "payment_method_type", n => { PaymentMethodType = n.GetStringValue(); } },
                { "payment_time", n => { PaymentTime = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("apply_to_commissions", ApplyToCommissions);
            writer.WriteDateTimeOffsetValue("external_create_time", ExternalCreateTime);
            writer.WriteStringValue("external_create_user", ExternalCreateUser);
            writer.WriteStringValue("external_source", ExternalSource);
            writer.WriteStringValue("external_source_value", ExternalSourceValue);
            writer.WriteStringValue("external_status_value", ExternalStatusValue);
            writer.WriteDateTimeOffsetValue("external_update_time", ExternalUpdateTime);
            writer.WriteStringValue("notes", Notes);
            writer.WriteDoubleValue("payment_amount", PaymentAmount);
            writer.WriteStringValue("payment_method_id", PaymentMethodId);
            writer.WriteStringValue("payment_method_type", PaymentMethodType);
            writer.WriteDateTimeOffsetValue("payment_time", PaymentTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
