// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RestOpportunityStage : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Stage checklist items</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Keap.OpenApiClient.Models.ChecklistItem>? ChecklistItems { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Keap.OpenApiClient.Models.ChecklistItem> ChecklistItems { get; set; }
#endif
        /// <summary>Creation timestamp (ISO-8601)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedTime { get; set; }
#nullable restore
#else
        public string CreatedTime { get; set; }
#endif
        /// <summary>Stage ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Stage name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Stage order in pipeline</summary>
        public int? Order { get; set; }
        /// <summary>Win probability (0-100)</summary>
        public int? Probability { get; set; }
        /// <summary>Target days in stage</summary>
        public int? TargetNumberDays { get; set; }
        /// <summary>Last update timestamp (ISO-8601)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedTime { get; set; }
#nullable restore
#else
        public string UpdatedTime { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Models.RestOpportunityStage"/> and sets the default values.
        /// </summary>
        public RestOpportunityStage()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.RestOpportunityStage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Keap.OpenApiClient.Models.RestOpportunityStage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Keap.OpenApiClient.Models.RestOpportunityStage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "checklist_items", n => { ChecklistItems = n.GetCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.ChecklistItem>(global::Soenneker.Keap.OpenApiClient.Models.ChecklistItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "created_time", n => { CreatedTime = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "order", n => { Order = n.GetIntValue(); } },
                { "probability", n => { Probability = n.GetIntValue(); } },
                { "target_number_days", n => { TargetNumberDays = n.GetIntValue(); } },
                { "updated_time", n => { UpdatedTime = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.ChecklistItem>("checklist_items", ChecklistItems);
            writer.WriteStringValue("created_time", CreatedTime);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("order", Order);
            writer.WriteIntValue("probability", Probability);
            writer.WriteIntValue("target_number_days", TargetNumberDays);
            writer.WriteStringValue("updated_time", UpdatedTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
