// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    /// <summary>Social account type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SocialAccountType
    {
        [EnumMember(Value = "SOCIAL_ACCOUNT_TYPE_UNSPECIFIED")]
        #pragma warning disable CS1591
        SocialAccountTypeUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "FACEBOOK")]
        #pragma warning disable CS1591
        Facebook,
        #pragma warning restore CS1591
        [EnumMember(Value = "LINKED_IN")]
        #pragma warning disable CS1591
        LinkedIn,
        #pragma warning restore CS1591
        [EnumMember(Value = "TWITTER")]
        #pragma warning disable CS1591
        Twitter,
        #pragma warning restore CS1591
        [EnumMember(Value = "INSTAGRAM")]
        #pragma warning disable CS1591
        Instagram,
        #pragma warning restore CS1591
        [EnumMember(Value = "SNAPCHAT")]
        #pragma warning disable CS1591
        Snapchat,
        #pragma warning restore CS1591
        [EnumMember(Value = "YOUTUBE")]
        #pragma warning disable CS1591
        Youtube,
        #pragma warning restore CS1591
        [EnumMember(Value = "PINTEREST")]
        #pragma warning disable CS1591
        Pinterest,
        #pragma warning restore CS1591
    }
}
