// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    /// <summary>
    /// Stage details
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StageDetails : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Stage checklist items</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Keap.OpenApiClient.Models.CheckListItemDetails>? ChecklistItems { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Keap.OpenApiClient.Models.CheckListItemDetails> ChecklistItems { get; set; }
#endif
        /// <summary>Win probability (0-100)</summary>
        public int? Probability { get; set; }
        /// <summary>Stage order in pipeline</summary>
        public int? StageOrder { get; set; }
        /// <summary>Target days in stage</summary>
        public int? TargetNumDays { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Models.StageDetails"/> and sets the default values.
        /// </summary>
        public StageDetails()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.StageDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Keap.OpenApiClient.Models.StageDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Keap.OpenApiClient.Models.StageDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "checklist_items", n => { ChecklistItems = n.GetCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.CheckListItemDetails>(global::Soenneker.Keap.OpenApiClient.Models.CheckListItemDetails.CreateFromDiscriminatorValue)?.AsList(); } },
                { "probability", n => { Probability = n.GetIntValue(); } },
                { "stage_order", n => { StageOrder = n.GetIntValue(); } },
                { "target_num_days", n => { TargetNumDays = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.CheckListItemDetails>("checklist_items", ChecklistItems);
            writer.WriteIntValue("probability", Probability);
            writer.WriteIntValue("stage_order", StageOrder);
            writer.WriteIntValue("target_num_days", TargetNumDays);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
