// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SubscriptionPlanList : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>If the subscription plan should be active/available for purchase</summary>
        public bool? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>How frequent to bill.</summary>
        public global::Soenneker.Keap.OpenApiClient.Models.SubscriptionPlanListBillingCycle? BillingCycle { get; set; }
        /// <summary>How many times per billing cycle to bill</summary>
        public int? BillingFrequency { get; set; }
        /// <summary>The subscription plan id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>How many billing cycles to bill. Optional field i.e. can be no value or 0.</summary>
        public int? NumberOfCycles { get; set; }
        /// <summary>Determines the order in which the plan will be displayed</summary>
        public int? OrderIndex { get; set; }
        /// <summary>The plan_price property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Keap.OpenApiClient.Models.CurrencyValueList? PlanPrice { get; set; }
#nullable restore
#else
        public global::Soenneker.Keap.OpenApiClient.Models.CurrencyValueList PlanPrice { get; set; }
#endif
        /// <summary>If the subscription plan should allow prorating</summary>
        public bool? Prorate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Models.SubscriptionPlanList"/> and sets the default values.
        /// </summary>
        public SubscriptionPlanList()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.SubscriptionPlanList"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Keap.OpenApiClient.Models.SubscriptionPlanList CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Keap.OpenApiClient.Models.SubscriptionPlanList();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "billing_cycle", n => { BillingCycle = n.GetEnumValue<global::Soenneker.Keap.OpenApiClient.Models.SubscriptionPlanListBillingCycle>(); } },
                { "billing_frequency", n => { BillingFrequency = n.GetIntValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "number_of_cycles", n => { NumberOfCycles = n.GetIntValue(); } },
                { "order_index", n => { OrderIndex = n.GetIntValue(); } },
                { "plan_price", n => { PlanPrice = n.GetObjectValue<global::Soenneker.Keap.OpenApiClient.Models.CurrencyValueList>(global::Soenneker.Keap.OpenApiClient.Models.CurrencyValueList.CreateFromDiscriminatorValue); } },
                { "prorate", n => { Prorate = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteEnumValue<global::Soenneker.Keap.OpenApiClient.Models.SubscriptionPlanListBillingCycle>("billing_cycle", BillingCycle);
            writer.WriteIntValue("billing_frequency", BillingFrequency);
            writer.WriteStringValue("id", Id);
            writer.WriteIntValue("number_of_cycles", NumberOfCycles);
            writer.WriteIntValue("order_index", OrderIndex);
            writer.WriteObjectValue<global::Soenneker.Keap.OpenApiClient.Models.CurrencyValueList>("plan_price", PlanPrice);
            writer.WriteBoolValue("prorate", Prorate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
