// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TaskObject : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Whether the task has been accepted</summary>
        public bool? Accepted { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Assigned user ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssignedToUserId { get; set; }
#nullable restore
#else
        public string AssignedToUserId { get; set; }
#endif
        /// <summary>Whether task is completed</summary>
        public bool? Completed { get; set; }
        /// <summary>Completion timestamp (ISO-8601)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompletionTime { get; set; }
#nullable restore
#else
        public string CompletionTime { get; set; }
#endif
        /// <summary>Associated contact ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactId { get; set; }
#nullable restore
#else
        public string ContactId { get; set; }
#endif
        /// <summary>Creator user ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedByUserId { get; set; }
#nullable restore
#else
        public string CreatedByUserId { get; set; }
#endif
        /// <summary>Creation timestamp (ISO-8601)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreateTime { get; set; }
#nullable restore
#else
        public string CreateTime { get; set; }
#endif
        /// <summary>Custom field values for the task</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Keap.OpenApiClient.Models.CustomFieldValueObject>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Keap.OpenApiClient.Models.CustomFieldValueObject> CustomFields { get; set; }
#endif
        /// <summary>Task description. Legacy XML-RPC name for this field was `CreationNotes`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Due date/time (ISO-8601)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DueTime { get; set; }
#nullable restore
#else
        public string DueTime { get; set; }
#endif
        /// <summary>Task ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>User who last updated the task.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastUpdatedByUserId { get; set; }
#nullable restore
#else
        public string LastUpdatedByUserId { get; set; }
#endif
        /// <summary>Last modification timestamp (ISO-8601)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModificationTime { get; set; }
#nullable restore
#else
        public string ModificationTime { get; set; }
#endif
        /// <summary>Associated opportunity ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OpportunityId { get; set; }
#nullable restore
#else
        public string OpportunityId { get; set; }
#endif
        /// <summary>Task priority</summary>
        public global::Soenneker.Keap.OpenApiClient.Models.TaskPriority? Priority { get; set; }
        /// <summary>Reminder minutes before due.</summary>
        public global::Soenneker.Keap.OpenApiClient.Models.TaskRemindTimeMins? RemindTimeMins { get; set; }
        /// <summary>Task title</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>Task type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Models.TaskObject"/> and sets the default values.
        /// </summary>
        public TaskObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.TaskObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Keap.OpenApiClient.Models.TaskObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Keap.OpenApiClient.Models.TaskObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accepted", n => { Accepted = n.GetBoolValue(); } },
                { "assigned_to_user_id", n => { AssignedToUserId = n.GetStringValue(); } },
                { "completed", n => { Completed = n.GetBoolValue(); } },
                { "completion_time", n => { CompletionTime = n.GetStringValue(); } },
                { "contact_id", n => { ContactId = n.GetStringValue(); } },
                { "create_time", n => { CreateTime = n.GetStringValue(); } },
                { "created_by_user_id", n => { CreatedByUserId = n.GetStringValue(); } },
                { "custom_fields", n => { CustomFields = n.GetCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.CustomFieldValueObject>(global::Soenneker.Keap.OpenApiClient.Models.CustomFieldValueObject.CreateFromDiscriminatorValue)?.AsList(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "due_time", n => { DueTime = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "last_updated_by_user_id", n => { LastUpdatedByUserId = n.GetStringValue(); } },
                { "modification_time", n => { ModificationTime = n.GetStringValue(); } },
                { "opportunity_id", n => { OpportunityId = n.GetStringValue(); } },
                { "priority", n => { Priority = n.GetEnumValue<global::Soenneker.Keap.OpenApiClient.Models.TaskPriority>(); } },
                { "remind_time_mins", n => { RemindTimeMins = n.GetEnumValue<global::Soenneker.Keap.OpenApiClient.Models.TaskRemindTimeMins>(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("accepted", Accepted);
            writer.WriteStringValue("assigned_to_user_id", AssignedToUserId);
            writer.WriteBoolValue("completed", Completed);
            writer.WriteStringValue("completion_time", CompletionTime);
            writer.WriteStringValue("contact_id", ContactId);
            writer.WriteStringValue("created_by_user_id", CreatedByUserId);
            writer.WriteStringValue("create_time", CreateTime);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Keap.OpenApiClient.Models.CustomFieldValueObject>("custom_fields", CustomFields);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("due_time", DueTime);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("last_updated_by_user_id", LastUpdatedByUserId);
            writer.WriteStringValue("modification_time", ModificationTime);
            writer.WriteStringValue("opportunity_id", OpportunityId);
            writer.WriteEnumValue<global::Soenneker.Keap.OpenApiClient.Models.TaskPriority>("priority", Priority);
            writer.WriteEnumValue<global::Soenneker.Keap.OpenApiClient.Models.TaskRemindTimeMins>("remind_time_mins", RemindTimeMins);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
