// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    /// <summary>
    /// The option is a user-defined free-form field. The settings define the restrictions on what can be entered.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TextOption : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether or not to allow whitespace in the text.</summary>
        public bool? AllowSpaces { get; set; }
        /// <summary>An error message to display if any rules are broken.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorMessage { get; set; }
#nullable restore
#else
        public string ErrorMessage { get; set; }
#endif
        /// <summary>Maximum allowable characters. Minimum is 0.</summary>
        public int? MaximumCharacters { get; set; }
        /// <summary>Minimum allowable characters. Minimum is 0.</summary>
        public int? MinimumCharacters { get; set; }
        /// <summary>Restricts the text to contain certain character types. Valid values are NONE, LETTER, DIGIT, BOTH.</summary>
        public global::Soenneker.Keap.OpenApiClient.Models.TextOptionOnlyContains? OnlyContains { get; set; }
        /// <summary>Restricts the text to end with certain character types. Valid values are NONE, LETTER, DIGIT, BOTH.</summary>
        public global::Soenneker.Keap.OpenApiClient.Models.TextOptionOnlyEndsWith? OnlyEndsWith { get; set; }
        /// <summary>Restricts the text to start with certain character types. Valid values are NONE, LETTER, DIGIT, BOTH.</summary>
        public global::Soenneker.Keap.OpenApiClient.Models.TextOptionOnlyStartsWith? OnlyStartsWith { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Models.TextOption"/> and sets the default values.
        /// </summary>
        public TextOption()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.TextOption"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Keap.OpenApiClient.Models.TextOption CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Keap.OpenApiClient.Models.TextOption();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allow_spaces", n => { AllowSpaces = n.GetBoolValue(); } },
                { "error_message", n => { ErrorMessage = n.GetStringValue(); } },
                { "maximum_characters", n => { MaximumCharacters = n.GetIntValue(); } },
                { "minimum_characters", n => { MinimumCharacters = n.GetIntValue(); } },
                { "only_contains", n => { OnlyContains = n.GetEnumValue<global::Soenneker.Keap.OpenApiClient.Models.TextOptionOnlyContains>(); } },
                { "only_ends_with", n => { OnlyEndsWith = n.GetEnumValue<global::Soenneker.Keap.OpenApiClient.Models.TextOptionOnlyEndsWith>(); } },
                { "only_starts_with", n => { OnlyStartsWith = n.GetEnumValue<global::Soenneker.Keap.OpenApiClient.Models.TextOptionOnlyStartsWith>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allow_spaces", AllowSpaces);
            writer.WriteStringValue("error_message", ErrorMessage);
            writer.WriteIntValue("maximum_characters", MaximumCharacters);
            writer.WriteIntValue("minimum_characters", MinimumCharacters);
            writer.WriteEnumValue<global::Soenneker.Keap.OpenApiClient.Models.TextOptionOnlyContains>("only_contains", OnlyContains);
            writer.WriteEnumValue<global::Soenneker.Keap.OpenApiClient.Models.TextOptionOnlyEndsWith>("only_ends_with", OnlyEndsWith);
            writer.WriteEnumValue<global::Soenneker.Keap.OpenApiClient.Models.TextOptionOnlyStartsWith>("only_starts_with", OnlyStartsWith);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
