// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TransactionV2 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The amount of the transaction.</summary>
        public double? Amount { get; set; }
        /// <summary>Contact associated with this order</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Keap.OpenApiClient.Models.BasicContact? Contact { get; set; }
#nullable restore
#else
        public global::Soenneker.Keap.OpenApiClient.Models.BasicContact Contact { get; set; }
#endif
        /// <summary>The id of the contact the transaction was for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactId { get; set; }
#nullable restore
#else
        public string ContactId { get; set; }
#endif
        /// <summary>A description of the transaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Any details if the transaction failed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorDetails { get; set; }
#nullable restore
#else
        public string ErrorDetails { get; set; }
#endif
        /// <summary>An external reference id - typically from a payment processor - that references this transaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalReferenceId { get; set; }
#nullable restore
#else
        public string ExternalReferenceId { get; set; }
#endif
        /// <summary>An external response code generated by payment processor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalResponseCode { get; set; }
#nullable restore
#else
        public string ExternalResponseCode { get; set; }
#endif
        /// <summary>If the transaction completed in a successful state. PENDING transactions are treated `false`.</summary>
        public bool? IsSuccessful { get; set; }
        /// <summary>The merchant account id through which the transaction was made.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MerchantAccountId { get; set; }
#nullable restore
#else
        public string MerchantAccountId { get; set; }
#endif
        /// <summary>The merchant account id through which the transaction was made.</summary>
        public global::Soenneker.Keap.OpenApiClient.Models.TransactionV2MerchantAccountType? MerchantAccountType { get; set; }
        /// <summary>List of order ids transaction was against.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? OrderIds { get; set; }
#nullable restore
#else
        public List<string> OrderIds { get; set; }
#endif
        /// <summary>Identifier of an order/invoice payment created by the transaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentId { get; set; }
#nullable restore
#else
        public string PaymentId { get; set; }
#endif
        /// <summary>Details of the payment method used for this transaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Keap.OpenApiClient.Models.PaymentMethod? PaymentMethod { get; set; }
#nullable restore
#else
        public global::Soenneker.Keap.OpenApiClient.Models.PaymentMethod PaymentMethod { get; set; }
#endif
        /// <summary>The resulting status of the transaction.</summary>
        public global::Soenneker.Keap.OpenApiClient.Models.TransactionV2Status? Status { get; set; }
        /// <summary>The method of transaction.</summary>
        public global::Soenneker.Keap.OpenApiClient.Models.TransactionV2TransactionMethod? TransactionMethod { get; set; }
        /// <summary>When this transaction was made. In ISO-8601 format.</summary>
        public DateTimeOffset? TransactionTime { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Keap.OpenApiClient.Models.TransactionV2"/> and sets the default values.
        /// </summary>
        public TransactionV2()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Keap.OpenApiClient.Models.TransactionV2"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Keap.OpenApiClient.Models.TransactionV2 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Keap.OpenApiClient.Models.TransactionV2();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetDoubleValue(); } },
                { "contact", n => { Contact = n.GetObjectValue<global::Soenneker.Keap.OpenApiClient.Models.BasicContact>(global::Soenneker.Keap.OpenApiClient.Models.BasicContact.CreateFromDiscriminatorValue); } },
                { "contact_id", n => { ContactId = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "error_details", n => { ErrorDetails = n.GetStringValue(); } },
                { "external_reference_id", n => { ExternalReferenceId = n.GetStringValue(); } },
                { "external_response_code", n => { ExternalResponseCode = n.GetStringValue(); } },
                { "is_successful", n => { IsSuccessful = n.GetBoolValue(); } },
                { "merchant_account_id", n => { MerchantAccountId = n.GetStringValue(); } },
                { "merchant_account_type", n => { MerchantAccountType = n.GetEnumValue<global::Soenneker.Keap.OpenApiClient.Models.TransactionV2MerchantAccountType>(); } },
                { "order_ids", n => { OrderIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "payment_id", n => { PaymentId = n.GetStringValue(); } },
                { "payment_method", n => { PaymentMethod = n.GetObjectValue<global::Soenneker.Keap.OpenApiClient.Models.PaymentMethod>(global::Soenneker.Keap.OpenApiClient.Models.PaymentMethod.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Keap.OpenApiClient.Models.TransactionV2Status>(); } },
                { "transaction_method", n => { TransactionMethod = n.GetEnumValue<global::Soenneker.Keap.OpenApiClient.Models.TransactionV2TransactionMethod>(); } },
                { "transaction_time", n => { TransactionTime = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("amount", Amount);
            writer.WriteObjectValue<global::Soenneker.Keap.OpenApiClient.Models.BasicContact>("contact", Contact);
            writer.WriteStringValue("contact_id", ContactId);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("error_details", ErrorDetails);
            writer.WriteStringValue("external_reference_id", ExternalReferenceId);
            writer.WriteStringValue("external_response_code", ExternalResponseCode);
            writer.WriteBoolValue("is_successful", IsSuccessful);
            writer.WriteStringValue("merchant_account_id", MerchantAccountId);
            writer.WriteEnumValue<global::Soenneker.Keap.OpenApiClient.Models.TransactionV2MerchantAccountType>("merchant_account_type", MerchantAccountType);
            writer.WriteCollectionOfPrimitiveValues<string>("order_ids", OrderIds);
            writer.WriteStringValue("payment_id", PaymentId);
            writer.WriteObjectValue<global::Soenneker.Keap.OpenApiClient.Models.PaymentMethod>("payment_method", PaymentMethod);
            writer.WriteEnumValue<global::Soenneker.Keap.OpenApiClient.Models.TransactionV2Status>("status", Status);
            writer.WriteEnumValue<global::Soenneker.Keap.OpenApiClient.Models.TransactionV2TransactionMethod>("transaction_method", TransactionMethod);
            writer.WriteDateTimeOffsetValue("transaction_time", TransactionTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
