// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UpdateCompanyUpdateMaskParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "company_name")]
        #pragma warning disable CS1591
        CompanyName,
        #pragma warning restore CS1591
        [EnumMember(Value = "address")]
        #pragma warning disable CS1591
        Address,
        #pragma warning restore CS1591
        [EnumMember(Value = "phone_number")]
        #pragma warning disable CS1591
        PhoneNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "fax_number")]
        #pragma warning disable CS1591
        FaxNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "email_address")]
        #pragma warning disable CS1591
        EmailAddress,
        #pragma warning restore CS1591
        [EnumMember(Value = "notes")]
        #pragma warning disable CS1591
        Notes,
        #pragma warning restore CS1591
        [EnumMember(Value = "website")]
        #pragma warning disable CS1591
        Website,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields")]
        #pragma warning disable CS1591
        CustomFields,
        #pragma warning restore CS1591
        [EnumMember(Value = "create_time")]
        #pragma warning disable CS1591
        CreateTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "update_time")]
        #pragma warning disable CS1591
        UpdateTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "anniversary_date")]
        #pragma warning disable CS1591
        AnniversaryDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "assistant_name")]
        #pragma warning disable CS1591
        AssistantName,
        #pragma warning restore CS1591
        [EnumMember(Value = "assistant_phone")]
        #pragma warning disable CS1591
        AssistantPhone,
        #pragma warning restore CS1591
        [EnumMember(Value = "billing_information")]
        #pragma warning disable CS1591
        BillingInformation,
        #pragma warning restore CS1591
        [EnumMember(Value = "birth_date")]
        #pragma warning disable CS1591
        BirthDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "contact_type")]
        #pragma warning disable CS1591
        ContactType,
        #pragma warning restore CS1591
        [EnumMember(Value = "first_name")]
        #pragma warning disable CS1591
        FirstName,
        #pragma warning restore CS1591
        [EnumMember(Value = "job_title")]
        #pragma warning disable CS1591
        JobTitle,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_name")]
        #pragma warning disable CS1591
        LastName,
        #pragma warning restore CS1591
        [EnumMember(Value = "middle_name")]
        #pragma warning disable CS1591
        MiddleName,
        #pragma warning restore CS1591
        [EnumMember(Value = "preferred_name")]
        #pragma warning disable CS1591
        PreferredName,
        #pragma warning restore CS1591
        [EnumMember(Value = "owner_id")]
        #pragma warning disable CS1591
        OwnerId,
        #pragma warning restore CS1591
        [EnumMember(Value = "referral_code")]
        #pragma warning disable CS1591
        ReferralCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "spouse_name")]
        #pragma warning disable CS1591
        SpouseName,
        #pragma warning restore CS1591
        [EnumMember(Value = "suffix")]
        #pragma warning disable CS1591
        Suffix,
        #pragma warning restore CS1591
        [EnumMember(Value = "title")]
        #pragma warning disable CS1591
        Title,
        #pragma warning restore CS1591
        [EnumMember(Value = "account_id")]
        #pragma warning disable CS1591
        AccountId,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_by")]
        #pragma warning disable CS1591
        CreatedBy,
        #pragma warning restore CS1591
        [EnumMember(Value = "groups")]
        #pragma warning disable CS1591
        Groups,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_updated_by")]
        #pragma warning disable CS1591
        LastUpdatedBy,
        #pragma warning restore CS1591
    }
}
