// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UpdateSubscriptionUpdateMaskParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "contact_id")]
        #pragma warning disable CS1591
        ContactId,
        #pragma warning restore CS1591
        [EnumMember(Value = "subscription_plan_id")]
        #pragma warning disable CS1591
        SubscriptionPlanId,
        #pragma warning restore CS1591
        [EnumMember(Value = "quantity")]
        #pragma warning disable CS1591
        Quantity,
        #pragma warning restore CS1591
        [EnumMember(Value = "billing_amount")]
        #pragma warning disable CS1591
        BillingAmount,
        #pragma warning restore CS1591
        [EnumMember(Value = "auto_charge")]
        #pragma warning disable CS1591
        AutoCharge,
        #pragma warning restore CS1591
        [EnumMember(Value = "max_charge_attempts")]
        #pragma warning disable CS1591
        MaxChargeAttempts,
        #pragma warning restore CS1591
        [EnumMember(Value = "days_between_retries")]
        #pragma warning disable CS1591
        DaysBetweenRetries,
        #pragma warning restore CS1591
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "billing_frequency")]
        #pragma warning disable CS1591
        BillingFrequency,
        #pragma warning restore CS1591
        [EnumMember(Value = "billing_cycle")]
        #pragma warning disable CS1591
        BillingCycle,
        #pragma warning restore CS1591
        [EnumMember(Value = "next_bill_date")]
        #pragma warning disable CS1591
        NextBillDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "end_date")]
        #pragma warning disable CS1591
        EndDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "payment_method_id")]
        #pragma warning disable CS1591
        PaymentMethodId,
        #pragma warning restore CS1591
        [EnumMember(Value = "allow_tax")]
        #pragma warning disable CS1591
        AllowTax,
        #pragma warning restore CS1591
        [EnumMember(Value = "lead_affiliate_id")]
        #pragma warning disable CS1591
        LeadAffiliateId,
        #pragma warning restore CS1591
        [EnumMember(Value = "sale_affiliate_id")]
        #pragma warning disable CS1591
        SaleAffiliateId,
        #pragma warning restore CS1591
        [EnumMember(Value = "promo_code")]
        #pragma warning disable CS1591
        PromoCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "shipping_option_id")]
        #pragma warning disable CS1591
        ShippingOptionId,
        #pragma warning restore CS1591
        [EnumMember(Value = "reason_stopped")]
        #pragma warning disable CS1591
        ReasonStopped,
        #pragma warning restore CS1591
        [EnumMember(Value = "shipping_address")]
        #pragma warning disable CS1591
        ShippingAddress,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_fields")]
        #pragma warning disable CS1591
        CustomFields,
        #pragma warning restore CS1591
    }
}
