// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UpdateCategoryDiscountUpdateMaskParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "description")]
        #pragma warning disable CS1591
        Description,
        #pragma warning restore CS1591
        [EnumMember(Value = "discount_percent")]
        #pragma warning disable CS1591
        DiscountPercent,
        #pragma warning restore CS1591
        [EnumMember(Value = "apply_to_commissions")]
        #pragma warning disable CS1591
        ApplyToCommissions,
        #pragma warning restore CS1591
        [EnumMember(Value = "criteria")]
        #pragma warning disable CS1591
        Criteria,
        #pragma warning restore CS1591
        [EnumMember(Value = "product_category_ids")]
        #pragma warning disable CS1591
        ProductCategoryIds,
        #pragma warning restore CS1591
    }
}
