// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    /// <summary>Strategy for applying discount: GROSS (before tax) or NET (after tax)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UpdateOrderTotalDiscountRequestDiscountStrategy
    {
        [EnumMember(Value = "GROSS")]
        #pragma warning disable CS1591
        Gross,
        #pragma warning restore CS1591
        [EnumMember(Value = "NET")]
        #pragma warning disable CS1591
        Net,
        #pragma warning restore CS1591
    }
}
