// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UpdateUserUpdateMaskParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "address")]
        #pragma warning disable CS1591
        Address,
        #pragma warning restore CS1591
        [EnumMember(Value = "company_name")]
        #pragma warning disable CS1591
        CompanyName,
        #pragma warning restore CS1591
        [EnumMember(Value = "email_address")]
        #pragma warning disable CS1591
        EmailAddress,
        #pragma warning restore CS1591
        [EnumMember(Value = "family_name")]
        #pragma warning disable CS1591
        FamilyName,
        #pragma warning restore CS1591
        [EnumMember(Value = "fax_numbers")]
        #pragma warning disable CS1591
        FaxNumbers,
        #pragma warning restore CS1591
        [EnumMember(Value = "given_name")]
        #pragma warning disable CS1591
        GivenName,
        #pragma warning restore CS1591
        [EnumMember(Value = "job_title")]
        #pragma warning disable CS1591
        JobTitle,
        #pragma warning restore CS1591
        [EnumMember(Value = "phone_numbers")]
        #pragma warning disable CS1591
        PhoneNumbers,
        #pragma warning restore CS1591
        [EnumMember(Value = "time_zone")]
        #pragma warning disable CS1591
        TimeZone,
        #pragma warning restore CS1591
        [EnumMember(Value = "website")]
        #pragma warning disable CS1591
        Website,
        #pragma warning restore CS1591
    }
}
