// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UpdateProductOptionListOptionValueUpdateMaskParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "item_label")]
        #pragma warning disable CS1591
        ItemLabel,
        #pragma warning restore CS1591
        [EnumMember(Value = "item_code")]
        #pragma warning disable CS1591
        ItemCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "item_display_order")]
        #pragma warning disable CS1591
        ItemDisplayOrder,
        #pragma warning restore CS1591
        [EnumMember(Value = "price_adjustment")]
        #pragma warning disable CS1591
        PriceAdjustment,
        #pragma warning restore CS1591
    }
}
