// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UpdateSubscriptionPlanUpdateMaskParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "allow_prorating")]
        #pragma warning disable CS1591
        AllowProrating,
        #pragma warning restore CS1591
        [EnumMember(Value = "cycle_type")]
        #pragma warning disable CS1591
        CycleType,
        #pragma warning restore CS1591
        [EnumMember(Value = "display_order_index")]
        #pragma warning disable CS1591
        DisplayOrderIndex,
        #pragma warning restore CS1591
        [EnumMember(Value = "frequency")]
        #pragma warning disable CS1591
        Frequency,
        #pragma warning restore CS1591
        [EnumMember(Value = "plan_price")]
        #pragma warning disable CS1591
        PlanPrice,
        #pragma warning restore CS1591
        [EnumMember(Value = "total_cycles")]
        #pragma warning disable CS1591
        TotalCycles,
        #pragma warning restore CS1591
    }
}
