// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Keap.OpenApiClient.Models
{
    /// <summary>The option that determines what happens after the form is submitted</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WebformExitOption
    {
        [EnumMember(Value = "REDIRECT")]
        #pragma warning disable CS1591
        Redirect,
        #pragma warning restore CS1591
        [EnumMember(Value = "FUNNEL_LINK")]
        #pragma warning disable CS1591
        FunnelLink,
        #pragma warning restore CS1591
        [EnumMember(Value = "HOSTED")]
        #pragma warning disable CS1591
        Hosted,
        #pragma warning restore CS1591
        [EnumMember(Value = "LANDING_PAGE")]
        #pragma warning disable CS1591
        LandingPage,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEB_FORM")]
        #pragma warning disable CS1591
        WebForm,
        #pragma warning restore CS1591
        [EnumMember(Value = "SURVEY")]
        #pragma warning disable CS1591
        Survey,
        #pragma warning restore CS1591
        [EnumMember(Value = "UPDATE")]
        #pragma warning disable CS1591
        Update,
        #pragma warning restore CS1591
        [EnumMember(Value = "UPDATE_OPT_OUT")]
        #pragma warning disable CS1591
        UpdateOptOut,
        #pragma warning restore CS1591
        [EnumMember(Value = "OPT_OUT")]
        #pragma warning disable CS1591
        OptOut,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONFIRM")]
        #pragma warning disable CS1591
        Confirm,
        #pragma warning restore CS1591
        [EnumMember(Value = "MESSAGE")]
        #pragma warning disable CS1591
        Message,
        #pragma warning restore CS1591
        [EnumMember(Value = "AUTHORING_MESSAGE")]
        #pragma warning disable CS1591
        AuthoringMessage,
        #pragma warning restore CS1591
        [EnumMember(Value = "MANUAL")]
        #pragma warning disable CS1591
        Manual,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLOSE")]
        #pragma warning disable CS1591
        Close,
        #pragma warning restore CS1591
        [EnumMember(Value = "DISPLAY_TEXT_AND_BUTTON")]
        #pragma warning disable CS1591
        DisplayTextAndButton,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "HOSTED_PAGE")]
        #pragma warning disable CS1591
        HostedPage,
        #pragma warning restore CS1591
    }
}
